# -*- coding: utf-8 -*-


{
    'name': 'ERP Integra - RH',
    'version': '1.0',
    'depends': [
        'base',
        'hr',
        'hr_contract',
        'hr_payroll',
        #'hr_holidays',
        'sped_base',
        'finan',
        #'integra_partner',
    ],
    'author': 'ERP Integra',
    'category': 'ERP Integra',
    'description': u'''ERP Integra - RH''',
    'init_xml': [
        #'data/hr.cbo.csv',
        #'data/res.bank.csv',
    ],
    'update_xml': [
        'security/groups.xml',
        'views/hr_menus_antigos.xml',
        'views/hr_view.xml',

        'views/partner_view.xml',

        'views/hr_employee_view.xml',
        'views/hr_afastamento.xml',
        'views/hr_job_view.xml',
        'views/hr_jornada_view.xml',
        'views/hr_salary_rule.xml',
        'views/hr_salary_rule_category.xml',
        'views/hr_contract_view.xml',
        #'views/hr_rescisao_simulacao.xml',
        'views/hr_holerite_variavel.xml',
        'views/hr_holerite_variavel_contrato.xml',
        'views/hr_rubrica_mes.xml',
        'views/hr_payroll_structure_view.xml',
        'views/rh_limpa_horlidays_view.xml',
        'views/hr_falta.xml',
        'views/hr_aviso_previo_proporcional.xml',
        'views/hr_rubrica_rescisao.xml',

        'views/hr_payslip_view.xml',
        'views/hr_decimo_terceiro.xml',
        'views/hr_aviso_previo.xml',
        'views/hr_aviso_ferias_view.xml',
        'views/hr_rescisao.xml',
        'views/hr_licenca_maternidade.xml',
        'views/hr_auxilio_acidente.xml',

        'views/hr_tabela_salario_minimo.xml',
        'views/hr_tabela_salario_familia.xml',
        'views/hr_tabela_inss.xml',
        'views/hr_tabela_ir.xml',
        'views/hr_tabela_ir_dependente.xml',
        'views/hr_tabela_rat.xml',

        #'views/hr_contract_alteracao.xml',
        'views/hr_contract_autonomo_view.xml',
        'views/hr_contract_prolabore_view.xml',
        'views/hr_contract_estagiario_view.xml',
        'views/hr_contract_aprendiz_view.xml',
        'views/hr_contract_funcionario_view.xml',
        'views/hr_contract_domestico_view.xml',

        'views/hr_contract_alteracao_remuneracao.xml',
        'views/hr_contract_alteracao_jornada.xml',
        'views/hr_contract_alteracao_cargo_atividade.xml',
        'views/hr_contract_alteracao_sindical.xml',
        'views/hr_contract_alteracao_lotacao.xml',
        'views/hr_contract_curso_treinamento.xml',
        'views/hr_reajuste_salarial_view.xml',
        'views/hr_reajuste_cargo_view.xml',

        'views/hr_lote_holerite.xml',
        'views/hr_lote_etiqueta.xml',
        'views/hr_lote_holerite_provisao.xml',
        'views/hr_holerite_variavel_media.xml',
        #'views/hr_tipo_dia.xml',
        'views/hr_motivo_alteracao_contratual.xml',
        'views/hr_employee_socio_view.xml',
        'views/hr_sindicato_view.xml',

        'wizard/hr_acoes_demoradas.xml',
        'wizard/recalcula_holerites.xml',
        'wizard/lote_holerites_wizard.xml',
        'wizard/efetiva_simulacao.xml',
        'wizard/fecha_holerites.xml',

        'wizard/hr_relatorio_listagem_ferias.xml',
        'wizard/hr_relatorio_listagem_ferias_vencidas.xml',
        'wizard/hr_relatorio_listagem_ferias_gozadas.xml',
        'wizard/hr_relatorio_listagem_afastamentos.xml',
        'wizard/hr_relatorio_listagem_funcionarios.xml',
        'wizard/hr_relatorio_listagem_tomadores_cnpj.xml',
        'wizard/hr_relatorio_listagem_tomadores_unidade.xml',
        'wizard/hr_relatorio_listagem_variaveis.xml',
        #'wizard/hr_relatorio_listagem_analitico.xml',
        'wizard/hr_relatorio_listagem_analitico.xml',
        'wizard/hr_relatorio_listagem_dependentes.xml',
        'wizard/hr_relatorio_listagem_mensalidade_sindical.xml',
        'wizard/hr_relatorio_listagem_seguros.xml',
        'wizard/hr_relatorio_funcionario_ativo_demitido.xml',
        'wizard/hr_relatorio_carteira_vigilante.xml',
        'wizard/hr_relatorio_pagamento_salario.xml',
        'wizard/hr_relatorio_resumo_cbo.xml',
        'wizard/hr_relatorio_irrf_empregado.xml',
        'wizard/hr_relatorio_dif_decimo.xml',
        'wizard/hr_comprovante_rendimentos_irpf.xml',
        'wizard/hr_pedido_demissao.xml',
        'wizard/hr_aviso_previo_trabalhado.xml',
        'wizard/hr_aviso_previo_indenizado.xml',
        'wizard/hr_relatorio_dados_funcionario.xml',
        'wizard/hr_relatorio_funcionario_admitidos.xml',
        'wizard/hr_ficha_financeira_por_funcionario.xml',
        'wizard/hr_relatorio_sindicato.xml',
        #'wizard/hr_relatorio_resumo_folha_por_rubrica.xml',
        #'wizard/hr_relatorio_calculo_gps.xml',
        'wizard/hr_relatorio_cargo_salario.xml',
        'wizard/hr_relatorio_estrutura_salario.xml',
        'wizard/hr_relatorio_regra_salario.xml',
        'wizard/hr_relatorio_hierarquico_salario.xml',
        #'wizard/hr_relatorio_folha.xml',
        'wizard/hr_relatorio_media_salario.xml',
        'wizard/hr_relatorio_salario_contribuicao.xml',
        'wizard/hr_relatorio_quadro_horario.xml',
        'wizard/hr_relatorio_provisao_ferias.xml',
        'wizard/hr_relatorio_provisao_13.xml',
        'wizard/hr_relatorio_curso_treinamento.xml',
        'wizard/hr_relatorio_irrf.xml',
        'wizard/hr_relatorio_aniversario.xml',
        'wizard/hr_relatorio_falta.xml',
        'wizard/hr_relatorio_exame.xml',
        'wizard/hr_relatorio_experiencia.xml',
        'wizard/hr_relatorio_endereco_funcionario.xml',
    ],
    'demo_xml': [],
    'installable': True,
    'active': False,

}
