insert into hr_categoria_trabalhador (codigo, descricao) values('101','Empregado – Geral');
insert into hr_categoria_trabalhador (codigo, descricao) values('102','Empregado – Trabalhador Rural por Pequeno Prazo da Lei 11.718/2008');
insert into hr_categoria_trabalhador (codigo, descricao) values('103','Empregado – Aprendiz');
insert into hr_categoria_trabalhador (codigo, descricao) values('104','Empregado – Doméstico');
insert into hr_categoria_trabalhador (codigo, descricao) values('105','Empregado – contrato a termo firmado nos termos da Lei 9601/98');
insert into hr_categoria_trabalhador (codigo, descricao) values('106','Empregado – contrato por prazo determinado nos termos da Lei 6019/74');
insert into hr_categoria_trabalhador (codigo, descricao) values('107','Trabalhador não vinculado ao RGPS com direito ao FGTS');
insert into hr_categoria_trabalhador (codigo, descricao) values('202','Trabalhador Avulso – Não Portuário (Informação do Sindicato)');
insert into hr_categoria_trabalhador (codigo, descricao) values('203','Trabalhador Avulso – Não Portuário (Informação do Contratante)');
insert into hr_categoria_trabalhador (codigo, descricao) values('301','Servidor Público – Titular de Cargo Efetivo');
insert into hr_categoria_trabalhador (codigo, descricao) values('302','Servidor Público – Ocupante de Cargo exclusivo em comissão');
insert into hr_categoria_trabalhador (codigo, descricao) values('303','Servidor Público – Exercente de Mandato Eletivo');
insert into hr_categoria_trabalhador (codigo, descricao) values('304','Servidor Público – Agente Público');
insert into hr_categoria_trabalhador (codigo, descricao) values('305','Servidor Público vinculado a RPPS indicado para conselho ou órgão representativo, na condição de representante do governo, órgão ou entidade da administração pública');
insert into hr_categoria_trabalhador (codigo, descricao) values('401','Dirigente Sindical – Em relação a Remuneração Recebida no Sindicato');
insert into hr_categoria_trabalhador (codigo, descricao) values('701','Contrib. Individual – Autônomo contratado por Empresas em geral');
insert into hr_categoria_trabalhador (codigo, descricao) values('702','Contrib. Individual – Autônomo contratado por Contrib. Individual, por pessoa física em geral, ou por missão diplomática e repartição consular de carreira estrangeiras');
insert into hr_categoria_trabalhador (codigo, descricao) values('703','Contrib. Individual – Autônomo contratado por Entidade Beneficente de Assistência Social isenta da cota patronal');
insert into hr_categoria_trabalhador (codigo, descricao) values('704','Excluído.');
insert into hr_categoria_trabalhador (codigo, descricao) values('711','Contrib. Individual – Transportador autônomo contratado por Empresas em geral');
insert into hr_categoria_trabalhador (codigo, descricao) values('712','Contrib. Individual – Transportador autônomo contratado por Contrib. Individual, por pessoa física em geral, ou por missão diplomática e repartição consular de carreira estrangeiras');
insert into hr_categoria_trabalhador (codigo, descricao) values('713','Contrib. Individual – Transportador autônomo contratado por Entidade Beneficente de Assistência Social isenta da cota patronal');
insert into hr_categoria_trabalhador (codigo, descricao) values('721','Contrib. Individual – Diretor não empregado com FGTS');
insert into hr_categoria_trabalhador (codigo, descricao) values('722','Contrib. Individual – Diretor não empregado sem FGTS');
insert into hr_categoria_trabalhador (codigo, descricao) values('731','Contrib. Individual – Cooperado que presta serviços a empresa por intermédio de cooperativa de trabalho');
insert into hr_categoria_trabalhador (codigo, descricao) values('732','Contrib. Individual – Cooperado que presta serviços a Entidade Beneficente de Assistência Social isenta da cota patronal ou para pessoa física');
insert into hr_categoria_trabalhador (codigo, descricao) values('733','Contrib. Individual – Cooperado eleito para direção da Cooperativa');
insert into hr_categoria_trabalhador (codigo, descricao) values('734','Contrib. Individual – Transportador Cooperado que presta serviços a empresa por intermédio de cooperativa de trabalho');
insert into hr_categoria_trabalhador (codigo, descricao) values('735','Contrib. Individual – Transportador Cooperado que presta serviços a Entidade Beneficente de Assistência Social isenta da cota patronal ou para pessoa física');
insert into hr_categoria_trabalhador (codigo, descricao) values('736','Contrib. Individual – Transportador Cooperado eleito para direção da Cooperativa');
insert into hr_categoria_trabalhador (codigo, descricao) values('741','Contrib. Individual – Cooperado filiado a cooperativa de produção');
insert into hr_categoria_trabalhador (codigo, descricao) values('751','Contrib. Individual – Micro Empreendedor Individual, quando contratado por PJ');
insert into hr_categoria_trabalhador (codigo, descricao) values('901','Estagiário');