insert into hr_rubrica_rescisao (codigo, descricao) values (50 , 'Saldo de Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (51 , 'Comissão'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (52 , 'Gratificação'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (53 , 'Adicional de Insalubridade'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (54 , 'Adicional de Periculosidade'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (55 , 'Adicional Noturno'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (56 , 'Horas Extras'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (57 , 'Gorjetas'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (58 , 'Descanso Semanal Remunerado (DSR)'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (59 , 'Reflexo do DSR sobre Salário Variável'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (60 , 'Multa Art. 477, § 8º/CLT'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (61 , 'Multa Art. 479/CLT'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (62 , 'SalárioFamília'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (63 , 'Décimo Terceiro Salário Proporcional'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (64 , 'Décimo Terceiro Salário Exercícios Anteriores'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (65 , 'Férias Proporcionais'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (66 , 'Férias Vencidas'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (67 , 'Férias Vencidas (Reflexo/Dobra)'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (68 , 'Terço Constitucional de Férias'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (69 , 'Aviso Prévio Indenizado'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (70 , 'Décimo Terceiro Salário (Aviso-Prévio Indenizado)'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (71 , 'Férias (Aviso-Prévio Indenizado)'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (72 , 'Percentagem'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (73 , 'Prêmios'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (74 , 'Viagens'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (75 , 'Sobreaviso'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (76 , 'Prontidão'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (77 , 'Adicional por Tempo de Serviço'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (78 , 'Adicional por Transferência de Localidade de Trabalho'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (79 , 'Salário Família Excedente ao Valor Legal'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (80 , 'Abono/Gratificação de Férias Excedente 20 Dias Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (81 , 'Valor Global Diárias para Viagem Excedente 50% Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (82 , 'Ajuda de Custo Art. 470/CLT'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (83 , 'Etapas Marítimos'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (84 , 'LicençaPrêmio Indenizada'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (85 , 'Quebra de Caixa'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (86 , 'Participação nos Lucros ou Resultados'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (87 , 'Indenização a Título de Incentivo à Demissão'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (88 , 'Bolsa Aprendizagem'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (89 , 'Abonos Desvinculados do Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (90 , 'Ganhos Eventuais Desvinculados do Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (91 , 'Reembolso Creche'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (92 , 'Reembolso Babá'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (93 , 'Gratificação Semestral'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (94 , 'Salário do Mês Anterior à Rescisão'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (95 , 'Outras Verbas'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (96 , 'Indenização Art. 9º, Lei nº 7.238/84'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (97 , 'Indenização Férias Escolares'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (98 , 'Multa do Art. 476-A, § 5º, da CLT'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (99 , 'Ajuste do saldo devedor.'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (100 , 'Pensão Alimentícia'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (101 , 'Adiantamento Salarial'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (102 , 'Adiantamento de 13º Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (103 , 'AvisoPrévio Indenizado'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (104 , 'Indenização Art. 480 CLT'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (105 , 'Empréstimo em Consignação'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (106 , 'Vale Transporte'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (107 , 'Reembolso do Vale Transporte'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (108 , 'Vale Alimentação'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (109 , 'Reembolso do Vale Alimentação'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (110 , 'Contribuição para o FAPI'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (111 , 'Contribuição Sindical Laboral'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (112.1 ,'Previdência Social'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (112.2 ,'Previdência Social 13º Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (113 , 'Contribuição Previdência Complementar'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (114.1 , 'IRRF'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (114.2 , 'IRRF sobre 13º Salário'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (114.3 , 'IRRF sobre Participação nos Lucros ou Resultados'  );
insert into hr_rubrica_rescisao (codigo, descricao) values (115 , 'Outros Descontos'  );
