# -*- coding: utf-8 -*-


#from __future__ import division, print_function, unicode_literals


{
    'name': 'Financeiro',
    'version': '1.0',
    'category': 'Integra',
    'description': u'Controle Financeiro BRASIL',
    'author': 'Integra',
    'maintainer': 'Integra',
    'website': 'http://www.Integra.inf.br',
    'depends': [
        'base',
        'email_template',
        'mail',
        'account',
        'sped_base',
        'project',
    ],
    'update_xml': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/finan_dashboard_view.xml',
        'views/finan_view.xml',

        'views/finan_formapagamento_view.xml',
        'views/finan_pagamento_view.xml',
        'views/account_payment_term.xml',
        'views/finan_motivobaixa_view.xml',
        'views/finan_conta_view.xml',
        'views/res_partner_bank.xml',
        'views/finan_carteira_view.xml',
        'views/finan_documento_view.xml',
        'views/finan_centrocusto_view.xml',
        'views/finan_receber_view.xml',
        'views/finan_pagar_view.xml',
        'views/finan_transacao_entrada_view.xml',
        'views/finan_transacao_saida_view.xml',
        'views/finan_transacao_transferencia_view.xml',
        'views/finan_remessa_view.xml',
        'views/finan_retorno_view.xml',
        'views/finan_caixa_view.xml',
        'views/finan_conciliacao_view.xml',
        'views/finan_lote_receber_view.xml',
        'views/finan_lote_pagar_view.xml',
        'views/finan_classificacao_cliente_view.xml',

        #
        # Dashboards
        #
        'views/finan_receber_dashboard_view.xml',
        'views/finan_pagar_dashboard_view.xml',

        'views/partner_view.xml',
        'views/account_account.xml',

        'wizard/finan_acoes_demoradas.xml',
        'wizard/finan_quitacao_wizard.xml',
        'wizard/finan_boletos_wizard.xml',
        'wizard/finan_nota_wizard.xml',
        'wizard/finan_saldos.xml',
        'wizard/finan_recibos_wizard.xml',
        'wizard/finan_ajusta_rateio_wizard.xml',
        'wizard/finan_saldo_banco.xml',
        'wizard/finan_altera_vencimento.xml',

        #'wizard/finan_relatorio_wizard.xml',
        'wizard/finan_relatorio_receber.xml',
        'wizard/finan_relatorio_receber_pagamentos.xml',
        'wizard/finan_relatorio_inadiplencia.xml',
        'wizard/finan_relatorio_pagar.xml',
        'wizard/finan_relatorio_pagar_pagamentos.xml',
        'wizard/finan_relatorio_diario_cliente.xml',
        'wizard/finan_relatorio_diario_fornecedor.xml',
        #'wizard/finan_relatorio_analitico.xml',
        'wizard/finan_relatorio_movimentacao.xml',
        'wizard/finan_relatorio_movimentacao_versao_2.xml',
        'wizard/finan_relatorio_extrato_cliente.xml',
        'wizard/finan_relatorio_extrato_fornecedor.xml',
        'wizard/finan_relatorio_fluxo_caixa_analitico.xml',
        'wizard/finan_relatorio_fluxo_caixa_sintetico.xml',
        'wizard/finan_relatorio_resumo_resultado.xml',
        'wizard/finan_relatorio_resultado_analitico.xml',
        'wizard/finan_relatorio_resultado_analitico_data.xml',
        'wizard/finan_relatorio_resultado_analitico_centrocusto.xml',
        #'wizard/finan_relatorio_notas_emitidas.xml',
        #'wizard/finan_relatorio_notas_canceladas.xml',
        'wizard/finan_relatorio_retencao_inss.xml',
        'wizard/finan_relatorio_razao_diario_cliente.xml',
        'wizard/finan_relatorio_razao_diario_fornecedor.xml',
        #'wizard/finan_relatorio_analise_contratos.xml',
        'wizard/finan_curva_abc.xml',
        'wizard/finan_relatorio_lancamentos_baixados.xml',
        'wizard/finan_relatorio_aging_receber.xml',
        'wizard/finan_relatorio_aging_pagar.xml',
        'wizard/finan_relatorio_plano_contas.xml',

    ],
    'init_xml': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'js': ['static/src/js/lib.js'],
    'qweb': ['static/src/xml/lib.xml'],
}
