# -*- coding: utf-8 -*-


{
    'name': 'eSocial',
    'version': '1.0',
    'category': 'Integra',
    'description': u'Tabelas do eSocial',
    'author': 'Integra',
    'maintainer': 'Integra',
    'website': 'http://www.Integra.inf.br',
    'depends': [
        'base',
        'hr',
        'sped_base',
        'integra_partner',
    ],
    'update_xml': [
        'views/esocial_menu_tabelas.xml',
        'views/esocial_tabela_01.xml',
        'views/esocial_tabela_02.xml',
        'views/esocial_tabela_03.xml',
        'views/esocial_tabela_04.xml',
        'views/esocial_tabela_05.xml',
        'views/esocial_tabela_06.xml',
        'views/esocial_tabela_07.xml',
        'views/esocial_tabela_08.xml',
        'views/esocial_tabela_09.xml',
        'views/esocial_tabela_10.xml',
        'views/esocial_tabela_11.xml',
        'views/esocial_tabela_12.xml',
        'views/esocial_tabela_13.xml',
        'views/esocial_tabela_14.xml',
        'views/esocial_tabela_15.xml',
        'views/esocial_tabela_16.xml',
        'views/esocial_tabela_17.xml',
        'views/esocial_tabela_18.xml',
        'views/esocial_tabela_19.xml',
        'views/esocial_tabela_20.xml',
        #'views/rh_caged_view.xml',

    ],
    'init_xml': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'js': ['static/src/js/lib.js'],
    'qweb': ['static/src/xml/lib.xml'],
}
