# -*- coding: utf-8 -*-


from __future__ import division, print_function, unicode_literals
from decimal import Decimal as D

#
# Definições para cálculo do ICMS próprio
#
MODALIDADE_BASE_ICMS_PROPRIO = (
    ('0', 'MARGEM DE VALOR AGREGADO (%) × VALOR DO PRODUTO'),
    ('1', 'PAUTA (R$) × QUANTIDADE'),
    ('2', 'PREÇO TABELADO MÁXIMO (R$) × QUANTIDADE'),
    ('3', 'VALOR DA OPERAÇÃO (R$) = QUANTIDADE × VALOR UNITÁRIO'),
)
MODALIDADE_BASE_ICMS_PROPRIO_DICT = dict(MODALIDADE_BASE_ICMS_PROPRIO)

MODALIDADE_BASE_ICMS_PROPRIO_MARGEM_VALOR_AGREGADO = '0'
MODALIDADE_BASE_ICMS_PROPRIO_PAUTA = '1'
MODALIDADE_BASE_ICMS_PROPRIO_PRECO_TABELADO_MAXIMO = '2'
MODALIDADE_BASE_ICMS_PROPRIO_VALOR_OPERACAO = '3'

MODALIDADE_BASE_ICMS_PROPRIO_PRECO_FIXO = (
    MODALIDADE_BASE_ICMS_PROPRIO_PAUTA,
    MODALIDADE_BASE_ICMS_PROPRIO_PRECO_TABELADO_MAXIMO,
)


#
# Definições para cálculo do ICMS recolhido por substituição tributária
#
MODALIDADE_BASE_ICMS_ST = (
    ('0', 'PREÇO TABELADO OU MÁXIMO SUGERIDO (R$) × QUANTIDADE'),
    ('1', 'LISTA NEGATIVA (R$) × QUANTIDADE'),
    ('2', 'LISTA POSITIVA (R$) × QUANTIDADE'),
    ('3', 'LISTA NEUTRA (R$) × QUANTIDADE'),
    ('4', 'MARGEM DE VALOR AGREGADO (%) × VALOR DO PRODUTO'),
    ('5', 'PAUTA (R$) × QUANTIDADE'),
)
MODALIDADE_BASE_ICMS_ST_DICT = dict(MODALIDADE_BASE_ICMS_ST)

MODALIDADE_BASE_ICMS_ST_PRECO_TABELADO_MAXIMO = '0'
MODALIDADE_BASE_ICMS_ST_LISTA_NEGATIVA = '1'
MODALIDADE_BASE_ICMS_ST_LISTA_POSITIVA = '2'
MODALIDADE_BASE_ICMS_ST_LISTA_NEUTRA = '3'
MODALIDADE_BASE_ICMS_ST_MARGEM_VALOR_AGREGADO = '4'
MODALIDADE_BASE_ICMS_ST_PAUTA = '5'

MODALIDADE_BASE_ICMS_ST_PRECO_FIXO = (
    MODALIDADE_BASE_ICMS_ST_PRECO_TABELADO_MAXIMO,
    MODALIDADE_BASE_ICMS_ST_LISTA_NEGATIVA,
    MODALIDADE_BASE_ICMS_ST_LISTA_POSITIVA,
    MODALIDADE_BASE_ICMS_ST_LISTA_NEUTRA,
    MODALIDADE_BASE_ICMS_ST_PAUTA,
)


#
# Definições para o cálculo do IPI
#

MODALIDADE_BASE_IPI = (
    ('0', 'TRIBUTACAO POR ALIQUOTA'),
    ('1', 'TRIBUTACAO POR QUANTIDADE'),
    )
MODALIDADE_BASE_IPI_DICT = dict(MODALIDADE_BASE_IPI)

MODALIDADE_BASE_IPI_ALIQUOTA = '0'
MODALIDADE_BASE_IPI_QUANTIDADE = '1'


#
# Definições para o cálculo do PIS e da COFINS
#
MODALIDADE_BASE_PIS = (
    ('0', 'TRIBUTAÇÃO POR ALÍQUOTA'),
    ('1', 'TRIBUTAÇÃO POR QUANTIDADE'),
    )
MODALIDADE_BASE_PIS_DICT = dict(MODALIDADE_BASE_PIS)

MODALIDADE_BASE_PIS_ALIQUOTA = '0'
MODALIDADE_BASE_PIS_QUANTIDADE = '1'

MODALIDADE_BASE_COFINS = MODALIDADE_BASE_PIS
MODALIDADE_BASE_COFINS_ALIQUOTA = MODALIDADE_BASE_PIS_ALIQUOTA
MODALIDADE_BASE_COFINS_QUANTIDADE = MODALIDADE_BASE_PIS_QUANTIDADE

#
# Definições para o cálculo do ISS
#
MODALIDADE_BASE_ISS = (
    ('0', 'TRIBUTAÇÃO POR ALÍQUOTA'),
    ('1', 'TRIBUTAÇÃO POR QUANTIDADE'),
    )
MODALIDADE_BASE_ISS_DICT = dict(MODALIDADE_BASE_ISS)

MODALIDADE_BASE_ISS_ALIQUOTA = '0'
MODALIDADE_BASE_ISS_QUANTIDADE = '1'


#
# Definições para a emissão e controle da NF-e
#
AMBIENTE_NFE = (
    ('1', 'PRODUCAO'),
    ('2', 'HOMOLOGACAO'),
)
AMBIENTE_NFE_DICT = dict(AMBIENTE_NFE)

AMBIENTE_NFE_PRODUCAO = '1'
AMBIENTE_NFE_HOMOLOGACAO = '2'


ENTRADA_SAIDA = (
    ('0', 'ENTRADA'),
    ('1', 'SAÍDA'),
)
ENTRADA_SAIDA_DICT = dict(ENTRADA_SAIDA)

ENTRADA_SAIDA_ENTRADA = '0'
ENTRADA_SAIDA_SAIDA = '1'


FINALIDADE_NFE = (
    ('1', 'NF-e NORMAL'),
    ('2', 'NF-e COMPLEMENTAR'),
    ('3', 'NF-e DE AJUSTE'),
    ('4', 'DEVOLUÇÃO DE MERCADORIA'),
)
FINALIDADE_NFE_DICT = dict(FINALIDADE_NFE)

FINALIDADE_NFE_NORMAL = '1'
FINALIDADE_NFE_COMPLEMENTAR = '2'
FINALIDADE_NFE_AJUSTE = '3'
FINALIDADE_NFE_DEVOLUCAO = '4'


FORMA_PAGAMENTO = (
    ('0', 'À VISTA'),
    ('1', 'A PRAZO'),
    ('2', 'OUTROS/SEM PAGAMENTO'),
)
FORMA_PAGAMENTO_DICT = dict(FORMA_PAGAMENTO)

FORMA_PAGAMENTO_A_VISTA = '0'
FORMA_PAGAMENTO_A_PRAZO = '1'
FORMA_PAGAMENTO_SEM_PAGAMENTO = '2'


MODALIDADE_FRETE = (
    ('0', 'DO EMITENTE'),
    ('1', 'DO DESTINATÁRIO'),
    ('2', 'DE TERCEIROS'),
    ('9', 'SEM FRETE'),
)
MODALIDADE_FRETE_DICT = dict(MODALIDADE_FRETE)

MODALIDADE_FRETE_EMITENTE = '0'
MODALIDADE_FRETE_DESTINATARIO = '1'
MODALIDADE_FRETE_TERCEIROS = '2'
MODALIDADE_FRETE_SEM_FRETE = '9'


MODELO_DOCUMENTO_ARRECADACAO = (
    ('0', 'DOCUMENTO ESTADUAL DE ARRECADACAO'),
    ('1', 'GNRE'),
    )
MODELO_DOCUMENTO_ARRECADACAO_DICT = dict(MODELO_DOCUMENTO_ARRECADACAO)

MODELO_DOCUMENTO_ARRECADACAO_DEA = '0'
MODELO_DOCUMENTO_ARRECADACAO_GNRE = '1'


MOTIVO_DESONERACAO_ICMS = (
    ('0', '0 - NÃO DESONERADO'),
    ('1', '1 - TÁXI'),
    ('2', '2 - DEFICIENTE FÍSICO'),
    ('3', '3 - PRODUTOR AGROPECUÁRIO'),
    ('4', '4 - FROTISTA/LOCADORA'),
    ('5', '5 - DIPLOMÁTICO/CONSULAR'),
    ('6', '6 - UTIL. E MOT. DA AMAZÔNIA OCIDENTAL E ÁREAS DE LIVRE COMÉRCIO'),
    ('7', '7 - SUFRAMA'),
    ('9', '9 - OUTROS'),
)
MOTIVO_DESONERACAO_ICMS_DICT = dict(MOTIVO_DESONERACAO_ICMS)

MOTIVO_DESONERACAO_ICMS_NAO_DESONERADO = '0'
MOTIVO_DESONERACAO_ICMS_TAXI = '1'
MOTIVO_DESONERACAO_ICMS_DEFICIENTE_FISICO = '2'
MOTIVO_DESONERACAO_ICMS_PRODUTOR_AGROPECUARIO = '3'
MOTIVO_DESONERACAO_ICMS_FROTISTA_LOCADORA = '4'
MOTIVO_DESONERACAO_ICMS_DIPLOMATICO_CONSULAR = '5'
MOTIVO_DESONERACAO_ICMS_UTILITARIOS_AMAZONIA = '6'
MOTIVO_DESONERACAO_ICMS_SUFRAMA = '7'
MOTIVO_DESONERACAO_ICMS_OUTROS = '9'


MODELO_FISCAL = (
    #('MERCADORIAS E SERVIÇOS', (
        ('65', 'NOTA FISCAL DE CONSUMIDOR ELETRÔNICA - NFC-e - 65'),
        ('2D', 'CUPOM FISCAL EMITIDO POR IMPRESSORA FISCAL - 2D'),
        ('2B', 'CUPOM FISCAL EMITIDO POR MÁQUINA REGISTRADORA - 2B'),
        ('2C', 'CUPOM FISCAL EMITIDO POR PONTO DE VENDA (PDV) - 2C'),
        ('01', 'NOTA FISCAL - 01 E 1A'),
        ('1B', 'NOTA FISCAL AVULSA - 1B'),
        ('04', 'NOTA FISCAL DE PRODUTOR RURAL - 04'),
        ('21', 'NOTA FISCAL DE SERV. DE COMUNICAÇÃO - 21'),
        ('22', 'NOTA FISCAL DE SERV. DE TELECOMUNICAÇÃO - 22'),
        ('07', 'NOTA FISCAL DE SERV. DE TRANSPORTE - 07'),
        ('27', 'NOTA FISCAL DE TRANSP. FERROVIÁRIO DE CARGAS - 27'),
        ('02', 'NOTA FISCAL DE VENDA A CONSUMIDOR - 02'),
        ('55', 'NOTA FISCAL ELETRÔNICA - NF-e - 55'),
        ('06', 'NOTA FISCAL/CONTA DE ENERGIA ELÉTRICA - 06'),
        ('29', 'NOTA FISCAL/CONTA DE FORNEC. DE ÁGUA CANALIZADA - 29'),
        ('28', 'NOTA FISCAL/CONTA DE FORNEC. DE GÁS CANALIZADO - 28'),
        ('18', 'RESUMO DE MOVIMENTO DIÁRIO - 18'),
        ('23', 'GNRE - 23'),
        #
        # Modelos não oficiais
        #
        ('SC', 'NOTA FISCAL DE SERVIÇO COMUM - SC'),
        ('SE', 'NOTA FISCAL DE SERVIÇO ELETRÔNICA - NFS-e - SE'),
        ('RL', 'RECIBO DE LOCAÇÃO - RL'),
        ('XX', 'OUTROS DOCUMENTOS NÃO FISCAIS - XX'),
        ('TF', 'ATUALIZAÇÃO DE TABELA DE FORNECEDOR'),
    #)),
    #('TRANSPORTE', (
        ('24', 'AUTORIZAÇÃO DE CARREGAMENTO E TRANSPORTE - 24'),
        ('14', 'BILHETE DE PASSAGEM AQUAVIÁRIO - 14'),
        ('15', 'BILHETE DE PASSAGEM E NOTA DE BAGAGEM -15'),
        ('2E', 'BILHETE DE PASSAGEM EMITIDO POR ECF - 2E'),
        ('16', 'BILHETE DE PASSAGEM FERROVIÁRIO - 16'),
        ('13', 'BILHETE DE PASSAGEM RODOVIÁRIO - 13'),
        ('30', 'BILHETE/RECIBO DO PASSAGEIRO - 30'),
        ('10', 'CONHECIMENTO AÉREO - 10'),
        ('09', 'CONHEC. DE TRANSPORTE AQUAVIÁRIO DE CARGAS - 09'),
        ('8B', 'CONHEC. DE TRANSPORTE DE CARGAS AVULSO - 8B'),
        ('57', 'CONHEC. DE TRANSPORTE ELETRÔNICO - CT-e - 57'),
        ('11', 'CONHEC. DE TRANSPORTE FERROVIÁRIO DE CARGAS - 11'),
        ('26', 'CONHEC. DE TRANSPORTE MULTIMODAL DE CARGAS - 26'),
        ('08', 'CONHEC. DE TRANSPORTE RODOVIÁRIO DE CARGAS - 08'),
        ('17', 'DESPACHO DE TRANSPORTE - 17'),
        ('25', 'MANIFESTO DE CARGA - 25'),
        ('20', 'ORDEM DE COLETA DE CARGA - 20'),
    #)),
)
MODELO_FISCAL_DICT = dict(MODELO_FISCAL)

MODELO_FISCAL_CUPOMFISCAL = (
    #('TRANSPORTE', (
        ('2E', 'BILHETE DE PASSAGEM EMITIDO POR ECF - 2E'),
    #)),
    #('MERCADORIAS E SERVICOS', (
        ('2D', 'CUPOM FISCAL EMITIDO POR IMPRESSORA FISCAL - 2D'),
        ('2B', 'CUPOM FISCAL EMITIDO POR MÁQUINA REGISTRADORA - 2B'),
        ('2C', 'CUPOM FISCAL EMITIDO POR PONTO DE VENDA (PDV) - 2C'),
        ('02', 'NOTA FISCAL DE VENDA A CONSUMIDOR - 02'),
    #)),
)
MODELO_FISCAL_CUPOMFISCAL_DICT = dict(MODELO_FISCAL_CUPOMFISCAL)

MODELO_FISCAL_NFE = '55'
MODELO_FISCAL_NFCE = '65'
MODELO_FISCAL_CUPOM_FISCAL_ECF = '2D'
MODELO_FISCAL_CTE = '57'


MODELO_FISCAL_REFERENCIADO = (
    ('55', 'NOTA FISCAL ELETRÔNICA - NF-e - 55'),
    ('01', 'NOTA FISCAL - 01, 1A'),
    ('1B', 'NOTA FISCAL AVULSA - 1B'),
    ('04', 'NOTA FISCAL DE PRODUTOR RURAL - 04'),
    ('2B', 'CUPOM FISCAL EMITIDO POR MÁQUINA REGISTRADORA - 2B'),
    ('2C', 'CUPOM FISCAL PDV - 2C'),
    ('2D', 'CUPOM FISCAL EMITIDO POR ECF - 2D'),
    ('57', 'CONHEC. DE TRANSPORTE ELETRÔNICO - CT-e - 57'),
)
MODELO_FISCAL_REFERENCIADO_DICT = dict(MODELO_FISCAL_REFERENCIADO)

MODELO_FISCAL_REFERENCIADO_FILTRO = (
    '55',
    '01',
    '1B',
    '04',
    '2B',
    '2C',
    '2D',
    '57',
    )

ORIGEM_MERCADORIA = (
    ('0', '0 - NACIONAL'),
    ('1', '1 - ESTRANGEIRA - IMPORTAÇÃO DIRETA'),
    ('2', '2 - ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO'),
    ('3', '3 - NACIONAL - CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 40%'),
    ('4', '4 - NACIONAL - PRODUÇÃO FEITA EM CONFORMIDADE COM OS PROCESSOS PRODUTIVOS BÁSICOS DE QUE TRATAM O DECRETO-LEI Nº 288/67, E AS LEIS NºS 8.248/91, 8.387/91, 10.176/01 E 11.484/07'),
    ('5', '5 - NACIONAL - CONTEÚDO DE IMPORTAÇÃO INFERIOR OU IGUAL A 40%'),
    ('6', '6 - ESTRANGEIRA - IMPORTAÇÃO DIRETA, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX'),
    ('7', '7 - ESTRANGEIRA - ADQUIRIDA NO MERCADO INTERNO, SEM SIMILAR NACIONAL, CONSTANTE EM LISTA DE RESOLUÇÃO CAMEX'),
    ('8', '8 - NACIONAL - CONTEÚDO DE IMPORTAÇÃO SUPERIOR A 70%'),
)
ORIGEM_MERCADORIA_DICT = dict(ORIGEM_MERCADORIA)

ORIGEM_MERCADORIA_NACIONAL = '0'
ORIGEM_MERCADORIA_IMPORTACAO_DIRETA = '1'
ORIGEM_MERCADORIA_IMPORTACAO_INDIRETA = '2'
ORIGEM_MERCADORIA_ALIQUOTA_4 = ['1', '2', '3', '8']


PROCESSO_EMISSAO_NFE = (
    ('0', 'CONTRIBUINTE - APLICATIVO PROPRIO'),
    ('1', 'FISCO - AVULSA'),
    ('2', 'CONTRIBUINTE - AVULSA'),
    ('3', 'CONTRIBUINTE - APLICATIVO DO FISCO'),
)
PROCESSO_EMISSAO_NFE_DICT = dict(PROCESSO_EMISSAO_NFE)

PROCESSO_EMISSAO_NFE_CONTRIBUINTE_PROPRIO = '0'
PROCESSO_EMISSAO_NFE_FISCO_AVULSA = '1'
PROCESSO_EMISSAO_NFE_CONTRIBUINTE_AVULSA = '2'
PROCESSO_EMISSAO_NFE_CONTRIBUINTE_APLICATIVO_FISCO = '3'


REGIME_TRIBUTARIO = (
    ('1', 'SIMPLES NACIONAL'),
    ('2', 'SIMPLES NACIONAL - EXCESSO DE SUBLIMITE DE RECEITA BRUTA'),
    ('3', 'REGIME NORMAL - LUCRO PRESUMIDO'),
    ('3.1', 'REGIME NORMAL - LUCRO REAL'),
)
REGIME_TRIBUTARIO_DICT = dict(REGIME_TRIBUTARIO)

REGIME_TRIBUTARIO_SIMPLES = '1'
REGIME_TRIBUTARIO_SIMPLES_EXCESSO = '2'
REGIME_TRIBUTARIO_NORMAL = '3'
REGIME_TRIBUTARIO_LUCRO_PRESUMIDO = '3'
REGIME_TRIBUTARIO_LUCRO_REAL = '3.1'

REGIME_TRIBUTARIO_OPERACAO_NORMAL = (
    ('2', 'SIMPLES NACIONAL - EXCESSO DE SUBLIMITE DE RECEITA BRUTA'),
    ('3', 'REGIME NORMAL'),
)
REGIME_TRIBUTARIO_OPERACAO_NORMAL_DICT = dict(REGIME_TRIBUTARIO_OPERACAO_NORMAL)

SITUACAO_FISCAL = (
    ('00', 'REGULAR'),
    ('01', 'REGULAR EXTEMPORÂNEO'),
    ('02', 'CANCELADO'),
    ('03', 'CANCELADO EXTEMPORÂNEO'),
    ('04', 'DENEGADO - NF-e OU CT-e'),
    ('05', 'NUMERAÇÃO INUTILIZADA - NF-e OU CT-e'),
    ('06', 'COMPLEMENTAR'),
    ('07', 'COMPLEMENTAR EXTEMPORÂNEO'),
    ('08', 'REGIME ESPECIAL OU NORMA ESPECÍFICA'),
    ('NC', 'MERCADORIA NÃO CIRCULOU'),
    ('MR', 'MERCADORIA NÃO RECEBIDA'),
)
SITUACAO_FISCAL_DICT = dict(SITUACAO_FISCAL)

SITUACAO_FISCAL_REGULAR = '00'
SITUACAO_FISCAL_REGULAR_EXTEMPORANEO = '01'
SITUACAO_FISCAL_CANCELADO = '02'
SITUACAO_FISCAL_CANCELADO_EXTEMPORANEO = '03'
SITUACAO_FISCAL_DENEGADO = '04'
SITUACAO_FISCAL_INUTILIZADO = '05'
SITUACAO_FISCAL_COMPLEMENTAR = '06'
SITUACAO_FISCAL_COMPLEMENTAR_EXTEMPORANEO = '07'
SITUACAO_FISCAL_REGIME_ESPECIAL = '08'
SITUACAO_FISCAL_MERCADORIA_NAO_CIRCULOU = 'NC'
SITUACAO_FISCAL_MERCADORIA_NAO_RECEBIDA = 'MR'

SITUACAO_FISCAL_SPED_CONSIDERA_CANCELADO = (
    SITUACAO_FISCAL_CANCELADO,
    SITUACAO_FISCAL_CANCELADO_EXTEMPORANEO,
    SITUACAO_FISCAL_DENEGADO,
    SITUACAO_FISCAL_INUTILIZADO,
)

SITUACAO_FISCAL_SPED_CONSIDERA_ATIVO = (
    SITUACAO_FISCAL_REGULAR,
    SITUACAO_FISCAL_REGULAR_EXTEMPORANEO,
    SITUACAO_FISCAL_COMPLEMENTAR,
    SITUACAO_FISCAL_COMPLEMENTAR_EXTEMPORANEO,
    SITUACAO_FISCAL_REGIME_ESPECIAL,
)

SITUACAO_FISCAL_EXTEMPORANEO = (
    SITUACAO_FISCAL_REGULAR_EXTEMPORANEO,
    SITUACAO_FISCAL_CANCELADO_EXTEMPORANEO,
    SITUACAO_FISCAL_COMPLEMENTAR_EXTEMPORANEO
)

ST_ICMS = (
    ('00', '00 - TRIBUTADA INTEGRALMENTE'),
    ('10', '10 - TRIBUTADA E COM COBRANÇA DE ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('20', '20 - COM REDUÇÃO DA BASE DE CÁLCULO'),
    ('30', '30 - ISENTA OU NÃO TRIBUTADA COM COBRANÇA DE ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('40', '40 - ISENTA'),
    ('41', '41 - NÃO TRIBUTADA'),
    ('50', '50 - SUSPENSÃO'),
    ('51', '51 - DIFERIMENTO'),
    ('60', '60 - ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('70', '70 - COM REDUÇÃO DA BASE DE CÁLCULO E COBRANÇA DO ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('90', '90 - OUTRAS'),
)
ST_ICMS_DICT = dict(ST_ICMS)

ST_ICMS_INTEGRAL = '00'
ST_ICMS_ST = '10'
ST_ICMS_REDUCAO = '20'
ST_ICMS_ISENTA_COM_ST = '30'
ST_ICMS_ISENTA = '40'
ST_ICMS_NAO_TRIBUTADA = '41'
ST_ICMS_SUSPENSAO = '50'
ST_ICMS_DIFERIMENTO = '51'
ST_ICMS_ANTERIOR = '60'
ST_ICMS_REDUCAO_COM_ST = '70'
ST_ICMS_OUTRAS = '90'
ST_ICMS_CALCULA_PROPRIO = (ST_ICMS_INTEGRAL, ST_ICMS_ST, ST_ICMS_REDUCAO, ST_ICMS_ISENTA_COM_ST, \
    ST_ICMS_ANTERIOR, ST_ICMS_REDUCAO_COM_ST)
ST_ICMS_COM_REDUCAO = (ST_ICMS_REDUCAO, ST_ICMS_ISENTA_COM_ST, \
    ST_ICMS_ANTERIOR, ST_ICMS_REDUCAO_COM_ST)
ST_ICMS_CALCULA_ST = (ST_ICMS_ST, ST_ICMS_ISENTA_COM_ST, ST_ICMS_REDUCAO_COM_ST)
ST_ICMS_ZERA_ICMS_PROPRIO = (ST_ICMS_ISENTA_COM_ST,)

ST_ICMS_SN = (
    ('101', '101 - TRIBUTADA COM PERMISSÃO DE CRÉDITO'),
    ('102', '102 - TRIBUTADA SEM PERMISSÃO DE CRÉDITO'),
    ('103', '103 - ISENTO DE ICMS PARA A FAIXA DE RECEITA BRUTA'),
    ('201', '201 - TRIBUTADA COM PERMISSÃO DE CRÉDIO E COBRANÇA DE ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('202', '202 - TRIBUTADA SEM PERMISSÃO DE CRÉDIO E COBRANÇA DE ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('203', '203 - ISENTO DE ICMS PARA A FAIXA DE RECEITA BRUTA E COBRANÇA DE ICMS POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('300', '300 - IMUNE'),
    ('400', '400 - NÃO TRIBUTADA PELO SIMPLES NACIONAL'),
    ('500', '500 - ICMS COBRADO ANTERIORMENTE POR SUBSTITUIÇÃO TRIBUTÁRIA OU POR ANTECIPAÇÃO'),
    ('900', '900 - OUTROS'),
)
ST_ICMS_SN_DICT = dict(ST_ICMS_SN)

ST_ICMS_SN_TRIB_COM_CREDITO = '101'
ST_ICMS_SN_TRIB_SEM_CREDITO = '102'
ST_ICMS_SN_ISENTO_ICMS = '103'
ST_ICMS_SN_TRIB_COM_CREDITO_COM_ST = '201'
ST_ICMS_SN_TRIB_SEM_CREDITO_COM_ST = '202'
ST_ICMS_SN_ISENTO_ICMS_COM_ST = '203'
ST_ICMS_SN_IMUNE = '300'
ST_ICMS_SN_NAO_TRIBUTADA = '400'
ST_ICMS_SN_ANTERIOR = '500'
ST_ICMS_SN_OUTRAS = '900'
ST_ICMS_SN_CALCULA_CREDITO = (ST_ICMS_SN_TRIB_COM_CREDITO, ST_ICMS_SN_TRIB_COM_CREDITO_COM_ST, ST_ICMS_SN_OUTRAS,)
ST_ICMS_SN_CALCULA_ST = (ST_ICMS_SN_TRIB_COM_CREDITO_COM_ST, ST_ICMS_SN_TRIB_SEM_CREDITO_COM_ST, ST_ICMS_SN_OUTRAS,)
ST_ICMS_SN_CALCULA_PROPRIO = (ST_ICMS_SN_OUTRAS,)

ST_ICMS_CODIGO_CEST = (ST_ICMS_ST, ST_ICMS_ISENTA_COM_ST, ST_ICMS_ANTERIOR, ST_ICMS_REDUCAO_COM_ST, ST_ICMS_OUTRAS, \
    ST_ICMS_SN_TRIB_COM_CREDITO_COM_ST, ST_ICMS_SN_TRIB_SEM_CREDITO_COM_ST, ST_ICMS_SN_ISENTO_ICMS_COM_ST, ST_ICMS_SN_ANTERIOR, ST_ICMS_SN_OUTRAS)


ST_IPI = (
    ('00', '00 - ENTRADA COM RECUPERAÇÃO DE CRÉDITO'),
    ('01', '01 - ENTRADA TRIBUTADA COM ALÍQUOTA ZERO'),
    ('02', '02 - ENTRADA ISENTA'),
    ('03', '03 - ENTRADA NÃO TRIBUTADA'),
    ('04', '04 - ENTRADA IMUNE'),
    ('05', '05 - ENTRADA COM SUSPENSÃO'),
    ('49', '49 - ENTRADA - OUTRAS ENTRADAS'),
    ('50', '50 - SAÍDA TRIBUTADA'),
    ('51', '51 - SAÍDA TRIBUTADA COM ALÍQUOTA ZERO'),
    ('52', '52 - SAÍDA ISENTA'),
    ('53', '53 - SAÍDA NÃO TRIBUTADA'),
    ('54', '54 - SAÍDA IMUNE'),
    ('55', '55 - SAÍDA COM SUSPENSÃO'),
    ('99', '99 - SAÍDA - OUTRAS SAÍDAS'),
    )
ST_IPI_DICT = dict(ST_IPI)

ST_IPI_ENTRADA = (
    ('00', '00 - ENTRADA COM RECUPERAÇÃO DE CRÉDITO'),
    ('01', '01 - ENTRADA TRIBUTADA COM ALÍQUOTA ZERO'),
    ('02', '02 - ENTRADA ISENTA'),
    ('03', '03 - ENTRADA NÃO TRIBUTADA'),
    ('04', '04 - ENTRADA IMUNE'),
    ('05', '05 - ENTRADA COM SUSPENSÃO'),
    ('49', '49 - ENTRADA - OUTRAS ENTRADAS'),
    )
ST_IPI_ENTRADA_DICT = dict(ST_IPI_ENTRADA)

ST_IPI_SAIDA = (
    ('50', '50 - SAÍDA TRIBUTADA'),
    ('51', '51 - SAÍDA TRIBUTADA COM ALÍQUOTA ZERO'),
    ('52', '52 - SAÍDA ISENTA'),
    ('53', '53 - SAÍDA NÃO TRIBUTADA'),
    ('54', '54 - SAÍDA IMUNE'),
    ('55', '55 - SAÍDA COM SUSPENSÃO'),
    ('99', '99 - SAÍDA - OUTRAS SAÍDAS'),
    )
ST_IPI_SAIDA_DICT = dict(ST_IPI_SAIDA)

ST_IPI_ENTRADA_RECUPERACAO_CREDITO = '00'
ST_IPI_ENTRADA_ALIQUOTA_ZERO = '01'
ST_IPI_ENTRADA_ISENTA = '02'
ST_IPI_ENTRADA_NAO_TRIBUTADA = '03'
ST_IPI_ENTRADA_IMUNE = '04'
ST_IPI_ENTRADA_SUSPENSAO = '05'
ST_IPI_ENTRADA_OUTRAS = '49'
ST_IPI_SAIDA_TRIBUTADA = '50'
ST_IPI_SAIDA_ALIQUOTA_ZERO = '51'
ST_IPI_SAIDA_ISENTA = '52'
ST_IPI_SAIDA_NAO_TRIBUTADA = '53'
ST_IPI_SAIDA_IMUNE = '54'
ST_IPI_SAIDA_SUSPENSAO = '55'
ST_IPI_SAIDA_OUTRAS = '99'
ST_IPI_CALCULA = (ST_IPI_ENTRADA_RECUPERACAO_CREDITO, ST_IPI_ENTRADA_OUTRAS, \
    ST_IPI_SAIDA_TRIBUTADA, ST_IPI_SAIDA_OUTRAS)


ST_ISS = (
    ('N', 'N - NORMAL'),
    ('R', 'R - RETIDO'),
    ('S', 'S - SUBSTITUTO'),
    ('I', 'I - ISENTO'),
)
ST_ISS_DICT = dict(ST_ISS)

ST_ISS_NORMAL = 'N'
ST_ISS_RETIDO = 'R'
ST_ISS_SUBSTITUTO = 'S'
ST_ISS_ISENTO = 'I'


ST_PIS = (
    ('01', '01 - TRIBUTÁVEL - BASE DE CÁLCULO = VALOR DA OPERAÇÃO ALÍQUOTA NORMAL (CUMULATIVO/NÃO CUMULATIVO)'),
    ('02', '02 - TRIBUTÁVEL - BASE DE CÁLCULO = VALOR DA OPERAÇÃO (ALÍQUOTA DIFERENCIADA)'),
    ('03', '03 - TRIBUTÁVEL - BASE DE CÁLCULO = QUANTIDADE VENDIDA × ALÍQUOTA POR UNIDADE DE PRODUTO'),
    ('04', '04 - TRIBUTÁVEL - TRIBUTAÇÃO MONOFÁSICA (ALÍQUOTA ZERO)'),
    ('05', '05 - TRIBUTÁVEL - SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('06', '06 - TRIBUTÁVEL - ALÍQUOTA ZERO'),
    ('07', '07 - ISENTA'),
    ('08', '08 - SEM INCIDÊNCIA'),
    ('09', '09 - COM SUSPENSÃO'),
    ('49', '49 - OUTRAS OPERAÇÕES DE SAÍDA'),
    ('50', '50 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'),
    ('51', '51 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NÃO TRIBUTADA NO MERCADO INTERNO'),
    ('52', '52 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'),
    ('53', '53 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'),
    ('54', '54 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('55', '55 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('56', '56 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'),
    ('60', '60 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'),
    ('61', '61 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'),
    ('62', '62 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'),
    ('63', '63 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'),
    ('64', '64 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('65', '65 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('66', '66 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'),
    ('67', '67 - CRÉDITO PRESUMIDO - OUTRAS OPERAÇÕES'),
    ('70', '70 - OPERAÇÃO DE AQUISIÇÃO SEM DIREITO A CRÉDITO'),
    ('71', '71 - OPERAÇÃO DE AQUISIÇÃO COM ISENÇÃO'),
    ('72', '72 - OPERAÇÃO DE AQUISIÇÃO COM SUSPENSÃO'),
    ('73', '73 - OPERAÇÃO DE AQUISIÇÃO A ALÍQUOTA ZERO'),
    ('74', '74 - OPERAÇÃO DE AQUISIÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'),
    ('75', '75 - OPERAÇÃO DE AQUISIÇÃO POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('98', '98 - OUTRAS OPERAÇÕES DE ENTRADA'),
    ('99', '99 - OUTRAS OPERAÇÕES'),
)
ST_PIS_DICT = dict(ST_PIS)

ST_PIS_ENTRADA = (
    ('50', '50 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'),
    ('51', '51 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA NÃO TRIBUTADA NO MERCADO INTERNO'),
    ('52', '52 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'),
    ('53', '53 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'),
    ('54', '54 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('55', '55 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('56', '56 - OPERAÇÃO COM DIREITO A CRÉDITO - VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'),
    ('60', '60 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA TRIBUTADA NO MERCADO INTERNO'),
    ('61', '61 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA NÃO-TRIBUTADA NO MERCADO INTERNO'),
    ('62', '62 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA EXCLUSIVAMENTE A RECEITA DE EXPORTAÇÃO'),
    ('63', '63 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO'),
    ('64', '64 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('65', '65 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS NÃO-TRIBUTADAS NO MERCADO INTERNO E DE EXPORTAÇÃO'),
    ('66', '66 - CRÉDITO PRESUMIDO - OPERAÇÃO DE AQUISIÇÃO VINCULADA A RECEITAS TRIBUTADAS E NÃO-TRIBUTADAS NO MERCADO INTERNO, E DE EXPORTAÇÃO'),
    ('67', '67 - CRÉDITO PRESUMIDO - OUTRAS OPERAÇÕES'),
    ('70', '70 - OPERAÇÃO DE AQUISIÇÃO SEM DIREITO A CRÉDITO'),
    ('71', '71 - OPERAÇÃO DE AQUISIÇÃO COM ISENÇÃO'),
    ('72', '72 - OPERAÇÃO DE AQUISIÇÃO COM SUSPENSÃO'),
    ('73', '73 - OPERAÇÃO DE AQUISIÇÃO A ALÍQUOTA ZERO'),
    ('74', '74 - OPERAÇÃO DE AQUISIÇÃO SEM INCIDÊNCIA DA CONTRIBUIÇÃO'),
    ('75', '75 - OPERAÇÃO DE AQUISIÇÃO POR SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('98', '98 - OUTRAS OPERAÇÕES DE ENTRADA'),
    )
ST_PIS_ENTRADA_DICT = dict(ST_PIS_ENTRADA)

ST_PIS_SAIDA = (
    ('01', '01 - TRIBUTÁVEL - BASE DE CÁLCULO = VALOR DA OPERAÇÃO ALÍQUOTA NORMAL (CUMULATIVO/NÃO CUMULATIVO)'),
    ('02', '02 - TRIBUTÁVEL - BASE DE CÁLCULO = VALOR DA OPERAÇÃO (ALÍQUOTA DIFERENCIADA)'),
    ('03', '03 - TRIBUTÁVEL - BASE DE CÁLCULO = QUANTIDADE VENDIDA × ALÍQUOTA POR UNIDADE DE PRODUTO'),
    ('04', '04 - TRIBUTÁVEL - TRIBUTAÇÃO MONOFÁSICA (ALÍQUOTA ZERO)'),
    ('05', '05 - TRIBUTÁVEL - SUBSTITUIÇÃO TRIBUTÁRIA'),
    ('06', '06 - TRIBUTÁVEL - ALÍQUOTA ZERO'),
    ('07', '07 - ISENTA'),
    ('08', '08 - SEM INCIDÊNCIA'),
    ('09', '09 - COM SUSPENSÃO'),
    ('49', '49 - OUTRAS OPERAÇÕES DE SAÍDA'),
    ('99', '99 - OUTRAS OPERAÇÕES'),
    )
ST_PIS_SAIDA_DICT = dict(ST_PIS_SAIDA)

ST_PIS_TRIB_NORMAL = '01'
ST_PIS_TRIB_DIFERENCIADA = '02'
ST_PIS_TRIB_QUANTIDADE = '03'
ST_PIS_TRIB_MONOFASICA = '04'
ST_PIS_TRIB_SUBSTITUICAO = '05'
ST_PIS_TRIB_ALIQUOTA_ZERO = '06'
ST_PIS_ISENTA = '07'
ST_PIS_SEM_INCIDENCIA = '08'
ST_PIS_COM_SUSPENSAO = '09'
ST_PIS_CRED_EXCL_TRIB_MERC_INTERNO = '50'
ST_PIS_CRED_EXCL_NAO_TRIB_MERC_INTERNO = '51'
ST_PIS_CRED_EXCL_EXPORTACAO = '52'
ST_PIS_CRED_TRIB_MERC_INTERNO = '53'
ST_PIS_CRED_TRIB_MERC_INTERNO_EXPORTACAO = '54'
ST_PIS_CRED_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '55'
ST_PIS_CRED_TRIB_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '56'
ST_PIS_CRED_PRESUMIDO_EXCL_TRIB_MERC_INTERNO = '60'
ST_PIS_CRED_PRESUMIDO_EXCL_NAO_TRIB_MERC_INTERNO = '61'
ST_PIS_CRED_PRESUMIDO_EXCL_EXPORTACAO = '62'
ST_PIS_CRED_PRESUMIDO_TRIB_MERC_INTERNO = '63'
ST_PIS_CRED_PRESUMIDO_TRIB_MERC_INTERNO_EXPORTACAO = '64'
ST_PIS_CRED_PRESUMIDO_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '65'
ST_PIS_CRED_PRESUMIDO_TRIB_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '66'
ST_PIS_CRED_PRESUMIDO_OUTRAS = '67'
ST_PIS_AQUIS_SEM_CREDITO = '70'
ST_PIS_AQUIS_ISENTA = '71'
ST_PIS_AQUIS_COM_SUSPENSAO = '72'
ST_PIS_AQUIS_ALIQUOTA_ZERO = '73'
ST_PIS_AQUIS_SEM_INCIDENCIA = '74'
ST_PIS_AQUIS_SUBSTITUICAO = '75'
ST_PIS_OUTRAS_ENTRADA = '98'
ST_PIS_OUTRAS = '99'
ST_PIS_CALCULA = (ST_PIS_TRIB_NORMAL, ST_PIS_TRIB_DIFERENCIADA, ST_PIS_TRIB_QUANTIDADE, ST_PIS_OUTRAS)
ST_PIS_CALCULA_CREDITO = (ST_PIS_CRED_EXCL_TRIB_MERC_INTERNO, ST_PIS_CRED_EXCL_NAO_TRIB_MERC_INTERNO, ST_PIS_CRED_EXCL_EXPORTACAO, ST_PIS_CRED_TRIB_MERC_INTERNO, ST_PIS_CRED_TRIB_MERC_INTERNO_EXPORTACAO, ST_PIS_CRED_NAO_TRIB_MERC_INTERNO_EXPORTACAO, ST_PIS_CRED_TRIB_NAO_TRIB_MERC_INTERNO_EXPORTACAO)
ST_PIS_CALCULA_ALIQUOTA = (ST_PIS_TRIB_NORMAL, ST_PIS_TRIB_DIFERENCIADA) + ST_PIS_CALCULA_CREDITO
ST_PIS_CALCULA_QUANTIDADE = (ST_PIS_TRIB_QUANTIDADE,)


ST_COFINS = ST_PIS
ST_COFINS_DICT = dict(ST_COFINS)
ST_COFINS_ENTRADA = ST_PIS_ENTRADA
ST_COFINS_ENTRADA_DICT = dict(ST_COFINS_ENTRADA)
ST_COFINS_SAIDA = ST_PIS_SAIDA
ST_COFINS_SAIDA_DICT = dict(ST_COFINS_SAIDA)
ST_COFINS_TRIB_NORMAL = '01'
ST_COFINS_TRIB_DIFERENCIADA = '02'
ST_COFINS_TRIB_QUANTIDADE = '03'
ST_COFINS_TRIB_MONOFASICA = '04'
ST_COFINS_TRIB_SUBSTITUICAO = '05'
ST_COFINS_TRIB_ALIQUOTA_ZERO = '06'
ST_COFINS_ISENTA = '07'
ST_COFINS_SEM_INCIDENCIA = '08'
ST_COFINS_COM_SUSPENSAO = '09'
ST_COFINS_CRED_EXCL_TRIB_MERC_INTERNO = '50'
ST_COFINS_CRED_EXCL_NAO_TRIB_MERC_INTERNO = '51'
ST_COFINS_CRED_EXCL_EXPORTACAO = '52'
ST_COFINS_CRED_TRIB_MERC_INTERNO = '53'
ST_COFINS_CRED_TRIB_MERC_INTERNO_EXPORTACAO = '54'
ST_COFINS_CRED_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '55'
ST_COFINS_CRED_TRIB_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '56'
ST_COFINS_CRED_PRESUMIDO_EXCL_TRIB_MERC_INTERNO = '60'
ST_COFINS_CRED_PRESUMIDO_EXCL_NAO_TRIB_MERC_INTERNO = '61'
ST_COFINS_CRED_PRESUMIDO_EXCL_EXPORTACAO = '62'
ST_COFINS_CRED_PRESUMIDO_TRIB_MERC_INTERNO = '63'
ST_COFINS_CRED_PRESUMIDO_TRIB_MERC_INTERNO_EXPORTACAO = '64'
ST_COFINS_CRED_PRESUMIDO_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '65'
ST_COFINS_CRED_PRESUMIDO_TRIB_NAO_TRIB_MERC_INTERNO_EXPORTACAO = '66'
ST_COFINS_CRED_PRESUMIDO_OUTRAS = '67'
ST_COFINS_AQUIS_SEM_CREDITO = '70'
ST_COFINS_AQUIS_ISENTA = '71'
ST_COFINS_AQUIS_COM_SUSPENSAO = '72'
ST_COFINS_AQUIS_ALIQUOTA_ZERO = '73'
ST_COFINS_AQUIS_SEM_INCIDENCIA = '74'
ST_COFINS_AQUIS_SUBSTITUICAO = '75'
ST_COFINS_OUTRAS_ENTRADA = '98'
ST_COFINS_OUTRAS = '99'
ST_COFINS_CALCULA = (ST_COFINS_TRIB_NORMAL, ST_COFINS_TRIB_DIFERENCIADA, ST_COFINS_TRIB_QUANTIDADE, ST_COFINS_OUTRAS)
ST_COFINS_CALCULA_ALIQUOTA = (ST_COFINS_TRIB_NORMAL, ST_COFINS_TRIB_DIFERENCIADA)
ST_COFINS_CALCULA_QUANTIDADE = (ST_COFINS_TRIB_QUANTIDADE,)


TIPO_EMISSAO = (
    ('0', 'EMISSÃO PRÓPRIA'),
    ('1', 'EMISSÃO POR TERCEIROS'),
    )
TIPO_EMISSAO_DICT = dict(TIPO_EMISSAO)

TIPO_EMISSAO_PROPRIA = '0'
TIPO_EMISSAO_TERCEIROS = '1'

TIPO_EMISSAO_TODAS = (
    ('%', 'TODAS'),
    ('0', 'EMISSÃO PRÓPRIA'),
    ('1', 'EMISSÃO POR TERCEIROS'),
    )
TIPO_EMISSAO_TODAS_DICT = dict(TIPO_EMISSAO_TODAS)


TIPO_EMISSAO_NFE = (
    ('1', 'NORMAL'),
    ('2', 'CONTINGÊNCIA FS-IA'),
    ('3', 'CONTINGÊNCIA SCAN'),
    ('4', 'CONTINGÊNCIA DPEC'),
    ('5', 'CONTINGÊNCIA FS-DA'),
    ('6', 'CONTINGÊNCIA SVC-AN'),
    ('7', 'CONTINGÊNCIA SVC-RS'),
    ('9', 'CONTINGÊNCIA OFFLINE NFC-e'),
)
TIPO_EMISSAO_NFE_DICT = dict(TIPO_EMISSAO_NFE)

TIPO_EMISSAO_NFE_NORMAL = '1'
TIPO_EMISSAO_NFE_CONTINGENCIA_FSIA = '2'
TIPO_EMISSAO_NFE_CONTINGENCIA_SCAN = '3'
TIPO_EMISSAO_NFE_CONTINGENCIA_DPEC = '4'
TIPO_EMISSAO_NFE_CONTINGENCIA_FSDA = '5'
TIPO_EMISSAO_NFE_CONTINGENCIA_SVCAN = '6'
TIPO_EMISSAO_NFE_CONTINGENCIA_SVCRS = '7'
TIPO_EMISSAO_NFE_CONTINGENCIA_OFFLINE_NFCE = '9'


TIPO_IMPRESSAO_NFE = (
    ('1', 'DANFE RETRATO'),
    ('2', 'DANFE PAISAGEM'),
    ('3', 'DANFE SIMPLIFICADO'),
    ('4', 'DANFE NFC-e'),
    ('5', 'DANFE NFC-e ELETRÔNICO'),
)
TIPO_IMPRESSAO_NFE_DICT = dict(TIPO_IMPRESSAO_NFE)

TIPO_IMPRESSAO_NFE_RETRATO = '1'
TIPO_IMPRESSAO_NFE_PAISAGEM = '2'
TIPO_IMPRESSAO_NFE_SIMPLIFICADO = '3'
TIPO_IMPRESSAO_NFCE_NORMAL = '4'
TIPO_IMPRESSAO_NFCE_ELETRONICO = '5'


VERSAO_NFE = (
    ('1.10', 'VERSÃO 1.10'),
    ('2.00', 'VERSÃO 2.00'),
    ('3.10', 'VERSÃO 3.10'),
)
VERSAO_NFE_DICT = dict(VERSAO_NFE)

VERSAO_NFE_110 = '1.10'
VERSAO_NFE_200 = '2.00'
VERSAO_NFE_310 = '3.10'


TIPO_PRODUTO_SERVICO = (
    ('00', 'MERCADORIA PARA REVENDA'),
    ('01', 'MATÉRIA-PRIMA'),
    ('02', 'EMBALAGEM'),
    ('03', 'PRODUTO EM PROCESSO'),
    ('04', 'PRODUTO ACABADO'),
    ('05', 'SUBPRODUTO'),
    ('06', 'PRODUTO INTERMEDIÁRIO'),
    ('07', 'MATERIAL DE USO E CONSUMO'),
    ('08', 'ATIVO IMOBILIZADO'),
    ('09', 'SERVIÇOS'),
    ('10', 'OUTROS INSUMOS'),
    ('99', 'OUTROS'),
    )
TIPO_PRODUTO_SERVICO_DICT = dict(TIPO_PRODUTO_SERVICO)

TIPO_PRODUTO_SERVICO_MERCADORIA_PARA_REVENDA = '00'
TIPO_PRODUTO_SERVICO_MATERIA_PRIMA = '01'
TIPO_PRODUTO_SERVICO_EMBALAGEM = '02'
TIPO_PRODUTO_SERVICO_PRODUTO_EM_PROCESSO = '03'
TIPO_PRODUTO_SERVICO_PRODUTO_ACABADO = '04'
TIPO_PRODUTO_SERVICO_SUBPRODUTO = '05'
TIPO_PRODUTO_SERVICO_PRODUTO_INTERMEDIARIO = '06'
TIPO_PRODUTO_SERVICO_MATERIAL_USO_CONSUMO = '07'
TIPO_PRODUTO_SERVICO_ATIVO_IMOBILIZADO = '08'
TIPO_PRODUTO_SERVICO_SERVICOS = '09'
TIPO_PRODUTO_SERVICO_OUTROS_INSUMOS = '10'
TIPO_PRODUTO_SERVICO_OUTROS = '99'


APURACAO_IPI = (
    ('0', 'MENSAL'),
    ('1', 'DECENDIAL'),
)
APURACAO_IPI_DICT = dict(APURACAO_IPI)

APURACAO_IPI_MENSAL = '0'
APURACAO_IPI_DECENDIAL = '1'


SITUACAO_NFE = (
    ('em_digitacao', 'EM DIGITAÇÃO'),
    ('a_enviar', 'AGUARDANDO ENVIO'),
    ('enviada', 'AGUARDANDO PROCESSAMENTO'),
    ('rejeitada', 'REJEITADA'),
    ('autorizada', 'AUTORIZADA'),
    ('cancelada', 'CANCELADA'),
    ('denegada', 'DENEGADA'),
    ('inutilizada', 'INUTILIZADA'),
)
SITUACAO_NFE_DICT = dict(SITUACAO_NFE)


NATUREZA_TRIBUTACAO_NFSE = (
    ('0', 'Tributada no município'),
    ('1', 'Tributada fora do município'),
    ('2', 'Isenta'),
    ('3', 'Imune'),
    ('4', 'Suspensa por decisão judicial'),
    ('5', 'Suspensa por procedimento administrativo'),
)

NAT_OP_TRIBUTADA_NO_MUNICIPIO = '0'
NAT_OP_TRIBUTADA_FORA_MUNICIPIO = '1'
NAT_OP_ISENTA = '2'
NAT_OP_IMUNE = '3'
NAT_OP_SUSPENSA_DECISAO_JUDICIAL = '4'
NAT_OP_SUSPENSA_PROCEDIMENTO_ADMINISTRATIVO = '5'


CLASSE_CONSUMO_ENERGIA = (
    ('01', 'COMERCIAL'),
    ('02', 'CONSUMO PRÓPRIO'),
    ('03', 'ILUMINAÇÃO PÚBLICA'),
    ('04', 'INDUSTRIAL'),
    ('05', 'PODER PÚBLICO'),
    ('06', 'RESIDENCIAL'),
    ('07', 'RURAL'),
    ('08', 'SERVIÇO PÚBLICO'),
)


TIPO_LIGACAO_ENERGIA = (
    ('1', 'MONOFÁSICA'),
    ('2', 'BIFÁSICA'),
    ('3', 'TRIFÁSICA'),
)


GRUPO_TENSAO_ENERGIA = (
    ('01', 'A1 - ALTA TENSÃO (230 kV OU MAIS)'),
    ('02', 'A2 - ALTA TENSÃO (88 A 138 kV)'),
    ('03', 'A3 - ALTA TENSÃO (69 kV)'),
    ('04', 'A3a - ALTA TENSÃO (30 kV A 44 kV)'),
    ('05', 'A4 - ALTA TENSÃO (2,3 kV A 25 kV)'),
    ('06', 'AS - ALTA TENSÃO SUBTERRÂNEO'),
    ('07', 'B1 - RESIDENCIAL'),
    ('08', 'B1 - RESIDENCIAL DE BAIXA RENDA'),
    ('09', 'B2 - RURAL'),
    ('10', 'B2 - COOPERATIVA DE ELETRIFICAÇÃO RURAL'),
    ('11', 'B2 - SERVIÇO PÚBLICO DE IRRIGAÇÃO'),
    ('12', 'B3 - DEMAIS CLASSES'),
    ('13', 'B4a - ILUMINAÇÃO PÚBLICA - REDE DE DISTRIBUIÇÃO'),
    ('14', 'B4b - ILUMINAÇÃO PÚBLICA - BULBO DE LÂMPADA'),
)


CLASSE_CONSUMO_GAS = CLASSE_CONSUMO_ENERGIA


CLASSE_CONSUMO_AGUA = (
    ('00', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL ATÉ R$ 50,00'),
    ('01', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 50,01 A R$ 100,00'),
    ('02', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 100,01 A R$ 200,00'),
    ('03', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 200,01 A R$ 300,00'),
    ('04', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 300,01 A R$ 400,00'),
    ('05', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 400,01 A R$ 500,00'),
    ('06', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL DE R$ 500,01 A R$ 1000,00'),
    ('07', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO RESIDENCIAL ACIMA DE R$ 1.000,01'),
    ('20', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL ATÉ R$ 50,00'),
    ('21', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 50,01 A R$ 100,00'),
    ('22', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 100,01 A R$ 200,00'),
    ('23', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 200,01 A R$ 300,00'),
    ('24', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 300,01 A R$ 400,00'),
    ('25', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 400,01 A R$ 500,00'),
    ('26', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO COMERCIAL/INDUSTRIAL DE R$ 500,01 A R$ 1.000,00'),
    ('27', '1 REGISTRO POR DOCUMENTO FISCAL DE CONSUMO COMERCIAL/INDUSTRIAL ACIMA DE R$ 1.000,01'),
    ('80', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE CONSUMO DE ÓRGÃO PÚBLICO'),
    ('90', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO ATÉ R$ 50,00'),
    ('91', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 50,01 A R$ 100,00'),
    ('92', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 100,01 A R$ 200,00'),
    ('93', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 200,01 A R$ 300,00'),
    ('94', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 300,01 A R$ 400,00'),
    ('95', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 400,01 A R$ 500,00'),
    ('96', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO DE R$ 500,01 A R$ 1.000,00'),
    ('97', '1 REGISTRO CONSOLIDANDO OS DOCUMENTOS DE OUTROS TIPOS DE CONSUMO ACIMA DE R$ 1.000,01'),
    ('99', '1 REGISTRO POR DOCUMENTO FISCAL EMITIDO'),
)

TIPO_ASSINANTE = (
    ('1', 'COMERCIAL/INDUSTRIAL'),
    ('2', 'PODER PÚBLICO'),
    ('3', 'RESIDENCIAL/PESSOA FÍSICA'),
    ('4', 'PÚBLICO'),
    ('5', 'SEMI-PÚBLICO'),
    ('6', 'OUTROS'),
)

#
# Definições da NF-e e NFC-e de 3ª geração
#
IDENTIFICACAO_DESTINO = (
    ('1', 'OPERAÇÃO INTERNA'),
    ('2', 'OPERAÇÃO INTERESTADUAL'),
    ('3', 'OPERAÇÃO COM EXTERIOR'),
)

IDENTIFICACAO_DESTINO_INTERNO = '1'
IDENTIFICACAO_DESTINO_INTERESTADUAL = '2'
IDENTIFICACAO_DESTINO_EXTERIOR = '3'

TIPO_CONSUMIDOR_FINAL = (
    ('0', 'NORMAL'),
    ('1', 'CONSUMIDOR FINAL'),
)

TIPO_CONSUMIDOR_FINAL_NORMAL = '0'
TIPO_CONSUMIDOR_FINAL_CONSUMIDOR_FINAL = '1'


INDICADOR_PRESENCA_COMPRADOR = (
    ('0', 'NÃO SE APLICA'),
    ('1', 'PRESENCIAL'),
    ('2', 'OPERAÇÃO PELA INTERNET'),
    ('3', 'OPERAÇÃO POR TELEATENDIMENTO'),
    ('4', 'PRESENCIAL - ENTREGA EM DOMICÍLIO'),
    ('9', 'NÃO PRESENCIAL - OUTROS'),
)

INDICADOR_PRESENCA_COMPRADOR_NAO_SE_APLICA = '0'
INDICADOR_PRESENCA_COMPRADOR_PRESENCIAL = '1'
INDICADOR_PRESENCA_COMPRADOR_INTERNET = '2'
INDICADOR_PRESENCA_COMPRADOR_TELEATENDIMENTO = '3'
INDICADOR_PRESENCA_COMPRADOR_ENTREGA_EM_DOMICILIO = '4'
INDICADOR_PRESENCA_COMPRADOR_OUTROS = '9'


INDICADOR_IE_DESTINATARIO = (
    ('1', 'CONTRIBUINTE ICMS'),
    ('2', 'CONTRIBUINTE ISENTO DE INSCRIÇÃO'),
    ('9', 'NÃO CONTRIBUINTE'),
)

INDICADOR_IE_DESTINATARIO_CONTRIBUINTE = '1'
INDICADOR_IE_DESTINATARIO_ISENTO = '2'
INDICADOR_IE_DESTINATARIO_NAO_CONTRIBUINTE = '9'

VIA_TRANSPORTE_IMPORTACAO = (
    ('1', 'MARÍTIMA'),
    ('1', 'FLUVIAL'),
    ('1', 'LACUSTRE'),
    ('1', 'AÉREA'),
    ('1', 'POSTAL'),
    ('1', 'FERROVIÁRIA'),
    ('1', 'RODOVIÁRIA'),
    ('1', 'REDE DE TRANSMISSÃO'),
    ('1', 'MEIOS PRÓPRIOS'),
    ('1', 'ENTRADA/SAÍDA FICTÍCIA'),
)

INTERMEDIACAO_IMPORTACAO = (
    ('1', 'POR CONTA PRÓPRIA'),
    ('2', 'POR CONTA E ORDEM'),
    ('3', 'POR ENCOMENDA'),
)

PROVEDOR_NFSE = (
    ('BETHA', u'Betha'),
    ('IPM', u'IPM'),
    ('PRODAM', u'Prodam'),
    ('BARUERI', u'Barueri'),
    ('JOINVILLE', u'Joinville'),
    ('BOANOTA', u'BoaNota Curitiba'),
    ('PUBLICA', u'Publica'),
    ('JOAO_PESSOA', u'João Pessoa'),
    #('ABRASF', u'ABRASF'),
    ('GINFES', u'GINFES'),
    ('NEOGRID', u'NeoGrid'),
    ('NOTA_CARIOCA', u'Rio Nota Carioca'),
    ('WEBISS', u'Webiss'),
    ('FOZ_IGUACU', u'Foz do Iguaçu'),
    ('GOVBR', u'GovBR'),
)

IE_DESTINATARIO = (
    ('1', 'CONTRIBUINTE'),
    ('2', 'ISENTO'),
    ('9', 'ESTRANGEIRO'),
)

ALIQUOTAS_ICMS = {
   'AC': {'AC': D('17'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'AL': {'AC': D('12'),'AL': D('18'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'AM': {'AC': D('12'),'AL': D('12'),'AM': D('17'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'AP': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('18'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'BA': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('18'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'CE': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('17'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'DF': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('18'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'ES': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('17'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'GO': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('17'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'MA': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('18'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'MT': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('17'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'MS': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('17'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'MG': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('18'),'PA': D( '7'),'PB': D( '7'),'PR': D('12'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('12'),'RJ': D('12'),'RO': D( '7'),'RR': D( '7'),'SC': D('12'),'SP': D('12'),'SE': D( '7'),'TO': D( '7')},
   'PA': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('17'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'PB': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('18'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'PR': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('12'),'PA': D( '7'),'PB': D( '7'),'PR': D('18'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('12'),'RJ': D('12'),'RO': D( '7'),'RR': D( '7'),'SC': D('12'),'SP': D('12'),'SE': D( '7'),'TO': D( '7')},
   'PE': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('18'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'PI': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('17'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'RN': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('18'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'RS': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('12'),'PA': D( '7'),'PB': D( '7'),'PR': D('12'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('18'),'RJ': D('12'),'RO': D( '7'),'RR': D( '7'),'SC': D('12'),'SP': D('12'),'SE': D( '7'),'TO': D( '7')},
   'RJ': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('12'),'PA': D( '7'),'PB': D( '7'),'PR': D('12'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('12'),'RJ': D('19'),'RO': D( '7'),'RR': D( '7'),'SC': D('12'),'SP': D('12'),'SE': D( '7'),'TO': D( '7')},
   'RO': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('17.5'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'RR': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('17'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('12')},
   'SC': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('12'),'PA': D( '7'),'PB': D( '7'),'PR': D('12'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('12'),'RJ': D('12'),'RO': D( '7'),'RR': D( '7'),'SC': D('17'),'SP': D('12'),'SE': D( '7'),'TO': D( '7')},
   'SP': {'AC': D( '7'),'AL': D( '7'),'AM': D( '7'),'AP': D( '7'),'BA': D( '7'),'CE': D( '7'),'DF': D( '7'),'ES': D( '7'),'GO': D( '7'),'MA': D( '7'),'MT': D( '7'),'MS': D( '7'),'MG': D('12'),'PA': D( '7'),'PB': D( '7'),'PR': D('12'),'PE': D( '7'),'PI': D( '7'),'RN': D( '7'),'RS': D('12'),'RJ': D('12'),'RO': D( '7'),'RR': D( '7'),'SC': D('12'),'SP': D('18'),'SE': D( '7'),'TO': D( '7')},
   'SE': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('18'),'TO': D('12')},
   'TO': {'AC': D('12'),'AL': D('12'),'AM': D('12'),'AP': D('12'),'BA': D('12'),'CE': D('12'),'DF': D('12'),'ES': D('12'),'GO': D('12'),'MA': D('12'),'MT': D('12'),'MS': D('12'),'MG': D('12'),'PA': D('12'),'PB': D('12'),'PR': D('12'),'PE': D('12'),'PI': D('12'),'RN': D('12'),'RS': D('12'),'RJ': D('12'),'RO': D('12'),'RR': D('12'),'SC': D('12'),'SP': D('12'),'SE': D('12'),'TO': D('18')},
}

#
# TABELA DE NATUREZA JURÍDICA 2014
#
NATURA_JURIDICA = (
       ('2011', u'Empresa Pública'),
       ('2038', u'Sociedade de Economia Mista'),
       ('2046', u'Sociedade Anônima Aberta'),
       ('2054', u'Sociedade Anônima Fechada'),
       ('2062', u'Sociedade Empresária Limitada'),
       ('2070', u'Sociedade Empresária em Nome Coletivo'),
       ('2089', u'Sociedade Empresária em Comandita Simples'),
       ('2097', u'Sociedade Empresária em Comandita por Ações'),
       ('2127', u'Sociedade em Conta de Participação'),
       ('2135', u'Empresário (Individual)'),
       ('2143', u'Cooperativa'),
       ('2151', u'Consórcio de Sociedades'),
       ('2160', u'Grupo de Sociedades'),
       ('2178', u'Estabelecimento, no Brasil, de Sociedade Estrangeira'),
       ('2194', u'Estabelecimento, no Brasil, de Empresa Binacional Argentino-Brasileira'),
       ('2216', u'Empresa Domiciliada no Exterior'),
       ('2224', u'Clube/Fundo de Investimento'),
       ('2232', u'Sociedade Simples Pura'),
       ('2240', u'Sociedade Simples Limitada'),
       ('2259', u'Sociedade Simples em Nome Coletivo'),
       ('2267', u'Sociedade Simples em Comandita Simples'),
       ('2275', u'Empresa Binacional'),
       ('2283', u'Consórcio de Empregadores'),
       ('2291', u'Consórcio Simples'),
       ('2305', u'Empresa Individual de Responsabilidade Limitada (de Natureza Empresária)'),
       ('2313', u'Empresa Individual de Responsabilidade Limitada (de Natureza Simples)'),
)


CFOPS_COMPRA_INDUSTRIALIZACAO = [
    '1101', '1111', '1116', '1120', '1122',         '1401', '1651',
    '2101', '2111', '2116', '2120', '2122',         '2401', '2651',
    '3101',                                 '3127',         '3651'
]

CFOPS_COMPRA_COMERCIALIZACAO = [
    '1102', '1113', '1117', '1118', '1121', '1403', '1652',
    '2102', '2113', '2117', '2118', '2121', '2403', '2652',
    '3102',                                         '3652'
]

CFOPS_COMPRA_ATIVO = [
    '1406', '1551',
    '2406', '2551',
            '3551',
]

CFOPS_USO_CONSUMO = [
    '1407', '1556',
    '2407', '2556',
            '3551',
]

CFOPS_COMPRA = CFOPS_COMPRA_INDUSTRIALIZACAO +  CFOPS_COMPRA_COMERCIALIZACAO + CFOPS_COMPRA_ATIVO + CFOPS_USO_CONSUMO
CFOPS_COMPRA_CUSTO_VENDA = CFOPS_COMPRA_INDUSTRIALIZACAO +  CFOPS_COMPRA_COMERCIALIZACAO



CFOPS_VENDA_MERCADORIA = [
    '5101', '5102', '5103', '5104', '5105', '5106', '5109', '5110', '5111', '5112', '5113', '5114', '5115', '5116', '5117', '5118', '5119', '5120', '5122', '5123', '5251', '5252', '5253', '5254', '5255', '5256', '5257', '5258', '5401', '5402', '5403', '5405', '5651', '5652', '5653', '5654', '5655', '5656', '5667',
    '6102', '6103', '6104', '6105', '6106', '6107', '6108', '6109', '6110', '6111', '6112', '6113', '6114', '6115', '6116', '6117', '6118', '6119', '6120', '6122', '6123', '6251', '6252', '6253', '6254', '6255', '6256', '6257', '6258', '6401', '6402', '6403', '6404', '6651', '6652', '6653', '6654', '6655', '6656', '6667', '6101',
    '7101', '7102', '7105', '7106', '7127', '7251', '7651', '7654', '7667',
]

CFOPS_VENDA_ATIVO = [
    '5551',
    '6551',
    '7551',
]

CFOPS_DEVOLUCAO_VENDA = [
    '1201', '1202', '1203', '1204', '1410', '1411', '1503', '1504', '1553', '1660', '1661', '1662',
    '2201', '2202', '2203', '2204', '2410', '2411', '2503', '2504', '2553', '2660', '2661', '2662',
    '3201', '3202', '3211',
]


CFOPS_CUSTO_ESTOQUE_VENDA_DEVOLUCAO = CFOPS_VENDA_MERCADORIA + CFOPS_VENDA_ATIVO + CFOPS_DEVOLUCAO_VENDA
#CFOPS_CUSTO_ESTOQUE_VENDA_DEVOLUCAO = CFOPS_VENDA_MERCADORIA + CFOPS_DEVOLUCAO_VENDA

CFOPS_DEVOLUCAO_COMPRA = [
    '5201', '5202', '5208', '5209', '5210', '5410', '5411', '5412', '5413', '5503', '5553', '5555', '5556', '5660', '5661', '5662', '5918', '5919', '5921',
    '6201', '6202', '6208', '6209', '6210', '6410', '6411', '6412', '6413', '6503', '6553', '6555', '6556', '6660', '6661', '6662', '6918', '6919', '6921',
    '7201', '7202', '7210', '7211', '7553', '7556', '7930',
]


#
# Tabelas do SIMPLES
#
CFOPS_VENDA_SERVICO = [
    '5933',
    '6933',
]
CFOPS_CALCULA_SIMPLES_NACIONAL = CFOPS_VENDA_MERCADORIA + CFOPS_VENDA_ATIVO + CFOPS_DEVOLUCAO_VENDA + CFOPS_VENDA_SERVICO

SIMPLES_NACIONAL_ANEXOS = (
    ('1', 'Anexo 1 - Comércio'),
    ('2', 'Anexo 2 - Indústria'),
    ('3', 'Anexo 3 - Serviços'),
    ('4', 'Anexo 4 - Serviços'),
    #('5', 'Anexo 5 - Serviços'),
    ('6', 'Anexo 6 - Serviços'),
)

SIMPLES_NACIONAL_TETO_01 = '180000'
SIMPLES_NACIONAL_TETO_02 = '360000'
SIMPLES_NACIONAL_TETO_03 = '540000'
SIMPLES_NACIONAL_TETO_04 = '720000'
SIMPLES_NACIONAL_TETO_05 = '900000'
SIMPLES_NACIONAL_TETO_06 = '1080000'
SIMPLES_NACIONAL_TETO_07 = '1260000'
SIMPLES_NACIONAL_TETO_08 = '1440000'
SIMPLES_NACIONAL_TETO_09 = '1620000'
SIMPLES_NACIONAL_TETO_10 = '1800000'
SIMPLES_NACIONAL_TETO_11 = '1980000'
SIMPLES_NACIONAL_TETO_12 = '2610000'
SIMPLES_NACIONAL_TETO_13 = '2340000'
SIMPLES_NACIONAL_TETO_14 = '2520000'
SIMPLES_NACIONAL_TETO_15 = '2700000'
SIMPLES_NACIONAL_TETO_16 = '2880000'
SIMPLES_NACIONAL_TETO_17 = '3060000'
SIMPLES_NACIONAL_TETO_18 = '3240000'
SIMPLES_NACIONAL_TETO_19 = '3420000'
SIMPLES_NACIONAL_TETO_20 = '3600000'


SIMPLES_NACIONAL_TETOS = (
    (SIMPLES_NACIONAL_TETO_01, 'De R$ 0,00 a R$ 180.000,00'),
    (SIMPLES_NACIONAL_TETO_02, 'De R$ 180.000,01 a R$ 360.000,00'),
    (SIMPLES_NACIONAL_TETO_03, 'De R$ 360.000,01 a R$ 540.000,00'),
    (SIMPLES_NACIONAL_TETO_04, 'De R$ 540.000,01 a R$ 720.000,00'),
    (SIMPLES_NACIONAL_TETO_05, 'De R$ 720.000,01 a R$ 900.000,00'),
    (SIMPLES_NACIONAL_TETO_06, 'De R$ 900.000,01 a R$ 1.080.000,00'),
    (SIMPLES_NACIONAL_TETO_07, 'De R$ 1.080.000,01 a R$ 1.260.000,00'),
    (SIMPLES_NACIONAL_TETO_08, 'De R$ 1.260.000,01 a R$ 1.440.000,00'),
    (SIMPLES_NACIONAL_TETO_09, 'De R$ 1.440.000,01 a R$ 1.620.000,00'),
    (SIMPLES_NACIONAL_TETO_10, 'De R$ 1.620.000,01 a R$ 1.800.000,00'),
    (SIMPLES_NACIONAL_TETO_11, 'De R$ 1.800.000,01 a R$ 1.980.000,00'),
    (SIMPLES_NACIONAL_TETO_12, 'De R$ 1.980.000,01 a R$ 2.160.000,00'),
    (SIMPLES_NACIONAL_TETO_13, 'De R$ 2.160.000,01 a R$ 2.340.000,00'),
    (SIMPLES_NACIONAL_TETO_14, 'De R$ 2.340.000,01 a R$ 2.520.000,00'),
    (SIMPLES_NACIONAL_TETO_15, 'De R$ 2.520.000,01 a R$ 2.700.000,00'),
    (SIMPLES_NACIONAL_TETO_16, 'De R$ 2.700.000,01 a R$ 2.880.000,00'),
    (SIMPLES_NACIONAL_TETO_17, 'De R$ 2.880.000,01 a R$ 3.060.000,00'),
    (SIMPLES_NACIONAL_TETO_18, 'De R$ 3.060.000,01 a R$ 3.240.000,00'),
    (SIMPLES_NACIONAL_TETO_19, 'De R$ 3.240.000,01 a R$ 3.420.000,00'),
    (SIMPLES_NACIONAL_TETO_20, 'De R$ 3.420.000,01 a R$ 3.600.000,00'),
)

SIMPLES_NACIONAL_ANEXO_01 = {
    SIMPLES_NACIONAL_TETO_01: {'al_simples':  D('4.00'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('0.00'), 'al_pis': D('0.00'), 'al_cpp': D('2.75'), 'al_icms': D('1.25'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_02: {'al_simples':  D('5.47'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('0.86'), 'al_pis': D('0.00'), 'al_cpp': D('2.75'), 'al_icms': D('1.86'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_03: {'al_simples':  D('6.84'), 'al_irpj': D('0.27'), 'al_csll': D('0.31'), 'al_cofins': D('0.95'), 'al_pis': D('0.23'), 'al_cpp': D('2.75'), 'al_icms': D('2.33'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_04: {'al_simples':  D('7.54'), 'al_irpj': D('0.35'), 'al_csll': D('0.35'), 'al_cofins': D('1.04'), 'al_pis': D('0.25'), 'al_cpp': D('2.99'), 'al_icms': D('2.56'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_05: {'al_simples':  D('7.60'), 'al_irpj': D('0.35'), 'al_csll': D('0.35'), 'al_cofins': D('1.05'), 'al_pis': D('0.25'), 'al_cpp': D('3.02'), 'al_icms': D('2.58'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_06: {'al_simples':  D('8.28'), 'al_irpj': D('0.38'), 'al_csll': D('0.38'), 'al_cofins': D('1.15'), 'al_pis': D('0.27'), 'al_cpp': D('3.28'), 'al_icms': D('2.82'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_07: {'al_simples':  D('8.36'), 'al_irpj': D('0.39'), 'al_csll': D('0.39'), 'al_cofins': D('1.16'), 'al_pis': D('0.28'), 'al_cpp': D('3.30'), 'al_icms': D('2.84'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_08: {'al_simples':  D('8.45'), 'al_irpj': D('0.39'), 'al_csll': D('0.39'), 'al_cofins': D('1.17'), 'al_pis': D('0.28'), 'al_cpp': D('3.35'), 'al_icms': D('2.87'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_09: {'al_simples':  D('9.03'), 'al_irpj': D('0.42'), 'al_csll': D('0.42'), 'al_cofins': D('1.25'), 'al_pis': D('0.30'), 'al_cpp': D('3.57'), 'al_icms': D('3.07'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_10: {'al_simples':  D('9.12'), 'al_irpj': D('0.43'), 'al_csll': D('0.43'), 'al_cofins': D('1.26'), 'al_pis': D('0.30'), 'al_cpp': D('3.60'), 'al_icms': D('3.10'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_11: {'al_simples':  D('9.95'), 'al_irpj': D('0.46'), 'al_csll': D('0.46'), 'al_cofins': D('1.38'), 'al_pis': D('0.33'), 'al_cpp': D('3.94'), 'al_icms': D('3.38'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_12: {'al_simples': D('10.04'), 'al_irpj': D('0.46'), 'al_csll': D('0.46'), 'al_cofins': D('1.39'), 'al_pis': D('0.33'), 'al_cpp': D('3.99'), 'al_icms': D('3.41'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_13: {'al_simples': D('10.13'), 'al_irpj': D('0.47'), 'al_csll': D('0.47'), 'al_cofins': D('1.40'), 'al_pis': D('0.33'), 'al_cpp': D('4.01'), 'al_icms': D('3.45'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_14: {'al_simples': D('10.23'), 'al_irpj': D('0.47'), 'al_csll': D('0.47'), 'al_cofins': D('1.42'), 'al_pis': D('0.34'), 'al_cpp': D('4.05'), 'al_icms': D('3.48'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_15: {'al_simples': D('10.32'), 'al_irpj': D('0.48'), 'al_csll': D('0.48'), 'al_cofins': D('1.43'), 'al_pis': D('0.34'), 'al_cpp': D('4.08'), 'al_icms': D('3.51'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_16: {'al_simples': D('11.23'), 'al_irpj': D('0.52'), 'al_csll': D('0.52'), 'al_cofins': D('1.56'), 'al_pis': D('0.37'), 'al_cpp': D('4.44'), 'al_icms': D('3.82'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_17: {'al_simples': D('11.32'), 'al_irpj': D('0.52'), 'al_csll': D('0.52'), 'al_cofins': D('1.57'), 'al_pis': D('0.37'), 'al_cpp': D('4.49'), 'al_icms': D('3.85'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_18: {'al_simples': D('11.42'), 'al_irpj': D('0.53'), 'al_csll': D('0.53'), 'al_cofins': D('1.58'), 'al_pis': D('0.38'), 'al_cpp': D('4.52'), 'al_icms': D('3.88'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_19: {'al_simples': D('11.51'), 'al_irpj': D('0.53'), 'al_csll': D('0.53'), 'al_cofins': D('1.60'), 'al_pis': D('0.38'), 'al_cpp': D('4.56'), 'al_icms': D('3.91'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_20: {'al_simples': D('11.61'), 'al_irpj': D('0.54'), 'al_csll': D('0.54'), 'al_cofins': D('1.60'), 'al_pis': D('0.38'), 'al_cpp': D('4.60'), 'al_icms': D('3.95'), 'al_iss': D('0.00')},
}

SIMPLES_NACIONAL_ANEXO_02 = {
    SIMPLES_NACIONAL_TETO_01: {'al_simples':  D('4.50'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('0.00'), 'al_pis': D('0.00'), 'al_cpp': D('2.75'), 'al_icms': D('1.25'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_02: {'al_simples':  D('5.97'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('0.86'), 'al_pis': D('0.00'), 'al_cpp': D('2.75'), 'al_icms': D('1.86'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_03: {'al_simples':  D('7.34'), 'al_irpj': D('0.27'), 'al_csll': D('0.31'), 'al_cofins': D('0.95'), 'al_pis': D('0.23'), 'al_cpp': D('2.75'), 'al_icms': D('2.33'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_04: {'al_simples':  D('8.04'), 'al_irpj': D('0.35'), 'al_csll': D('0.35'), 'al_cofins': D('1.04'), 'al_pis': D('0.25'), 'al_cpp': D('2.99'), 'al_icms': D('2.56'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_05: {'al_simples':  D('8.10'), 'al_irpj': D('0.35'), 'al_csll': D('0.35'), 'al_cofins': D('1.05'), 'al_pis': D('0.25'), 'al_cpp': D('3.02'), 'al_icms': D('2.58'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_06: {'al_simples':  D('8.78'), 'al_irpj': D('0.38'), 'al_csll': D('0.38'), 'al_cofins': D('1.15'), 'al_pis': D('0.27'), 'al_cpp': D('3.28'), 'al_icms': D('2.82'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_07: {'al_simples':  D('8.86'), 'al_irpj': D('0.39'), 'al_csll': D('0.39'), 'al_cofins': D('1.16'), 'al_pis': D('0.28'), 'al_cpp': D('3.30'), 'al_icms': D('2.84'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_08: {'al_simples':  D('8.95'), 'al_irpj': D('0.39'), 'al_csll': D('0.39'), 'al_cofins': D('1.17'), 'al_pis': D('0.28'), 'al_cpp': D('3.35'), 'al_icms': D('2.87'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_09: {'al_simples':  D('9.53'), 'al_irpj': D('0.42'), 'al_csll': D('0.42'), 'al_cofins': D('1.25'), 'al_pis': D('0.30'), 'al_cpp': D('3.57'), 'al_icms': D('3.07'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_10: {'al_simples':  D('9.62'), 'al_irpj': D('0.42'), 'al_csll': D('0.42'), 'al_cofins': D('1.26'), 'al_pis': D('0.30'), 'al_cpp': D('3.62'), 'al_icms': D('3.10'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_11: {'al_simples': D('10.45'), 'al_irpj': D('0.46'), 'al_csll': D('0.46'), 'al_cofins': D('1.38'), 'al_pis': D('0.33'), 'al_cpp': D('3.94'), 'al_icms': D('3.38'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_12: {'al_simples': D('10.54'), 'al_irpj': D('0.46'), 'al_csll': D('0.46'), 'al_cofins': D('1.39'), 'al_pis': D('0.33'), 'al_cpp': D('3.99'), 'al_icms': D('3.41'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_13: {'al_simples': D('10.63'), 'al_irpj': D('0.47'), 'al_csll': D('0.47'), 'al_cofins': D('1.40'), 'al_pis': D('0.33'), 'al_cpp': D('4.01'), 'al_icms': D('3.45'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_14: {'al_simples': D('10.73'), 'al_irpj': D('0.47'), 'al_csll': D('0.47'), 'al_cofins': D('1.42'), 'al_pis': D('0.34'), 'al_cpp': D('4.05'), 'al_icms': D('3.48'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_15: {'al_simples': D('10.82'), 'al_irpj': D('0.48'), 'al_csll': D('0.48'), 'al_cofins': D('1.43'), 'al_pis': D('0.34'), 'al_cpp': D('4.08'), 'al_icms': D('3.51'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_16: {'al_simples': D('11.73'), 'al_irpj': D('0.52'), 'al_csll': D('0.52'), 'al_cofins': D('1.56'), 'al_pis': D('0.37'), 'al_cpp': D('4.44'), 'al_icms': D('3.82'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_17: {'al_simples': D('11.82'), 'al_irpj': D('0.52'), 'al_csll': D('0.52'), 'al_cofins': D('1.57'), 'al_pis': D('0.37'), 'al_cpp': D('4.49'), 'al_icms': D('3.85'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_18: {'al_simples': D('11.92'), 'al_irpj': D('0.53'), 'al_csll': D('0.53'), 'al_cofins': D('1.58'), 'al_pis': D('0.38'), 'al_cpp': D('4.52'), 'al_icms': D('3.88'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_19: {'al_simples': D('12.01'), 'al_irpj': D('0.53'), 'al_csll': D('0.53'), 'al_cofins': D('1.60'), 'al_pis': D('0.38'), 'al_cpp': D('4.56'), 'al_icms': D('3.91'), 'al_iss': D('0.50')},
    SIMPLES_NACIONAL_TETO_20: {'al_simples': D('12.11'), 'al_irpj': D('0.54'), 'al_csll': D('0.54'), 'al_cofins': D('1.60'), 'al_pis': D('0.38'), 'al_cpp': D('4.60'), 'al_icms': D('3.95'), 'al_iss': D('0.50')},
}

SIMPLES_NACIONAL_ANEXO_03 = {
    SIMPLES_NACIONAL_TETO_01: {'al_simples':  D('6.00'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('0.00'), 'al_pis': D('0.00'), 'al_cpp': D('4.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_02: {'al_simples':  D('8.21'), 'al_irpj': D('0.00'), 'al_csll': D('0.00'), 'al_cofins': D('1.42'), 'al_pis': D('0.00'), 'al_cpp': D('4.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_03: {'al_simples': D('10.26'), 'al_irpj': D('0.48'), 'al_csll': D('0.43'), 'al_cofins': D('1.43'), 'al_pis': D('0.35'), 'al_cpp': D('4.07'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_04: {'al_simples': D('11.31'), 'al_irpj': D('0.53'), 'al_csll': D('0.53'), 'al_cofins': D('1.56'), 'al_pis': D('0.38'), 'al_cpp': D('4.47'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_05: {'al_simples': D('11.40'), 'al_irpj': D('0.53'), 'al_csll': D('0.52'), 'al_cofins': D('1.58'), 'al_pis': D('0.38'), 'al_cpp': D('4.52'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_06: {'al_simples': D('12.42'), 'al_irpj': D('0.57'), 'al_csll': D('0.57'), 'al_cofins': D('1.73'), 'al_pis': D('0.40'), 'al_cpp': D('4.92'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_07: {'al_simples': D('12.54'), 'al_irpj': D('0.59'), 'al_csll': D('0.56'), 'al_cofins': D('1.74'), 'al_pis': D('0.42'), 'al_cpp': D('4.97'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_08: {'al_simples': D('12.68'), 'al_irpj': D('0.59'), 'al_csll': D('0.57'), 'al_cofins': D('1.76'), 'al_pis': D('0.42'), 'al_cpp': D('5.03'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_09: {'al_simples': D('13.55'), 'al_irpj': D('0.63'), 'al_csll': D('0.61'), 'al_cofins': D('1.88'), 'al_pis': D('0.45'), 'al_cpp': D('5.37'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_10: {'al_simples': D('13.68'), 'al_irpj': D('0.63'), 'al_csll': D('0.64'), 'al_cofins': D('1.89'), 'al_pis': D('0.45'), 'al_cpp': D('5.42'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_11: {'al_simples': D('14.93'), 'al_irpj': D('0.69'), 'al_csll': D('0.69'), 'al_cofins': D('2.07'), 'al_pis': D('0.50'), 'al_cpp': D('5.98'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_12: {'al_simples': D('15.06'), 'al_irpj': D('0.69'), 'al_csll': D('0.69'), 'al_cofins': D('2.09'), 'al_pis': D('0.50'), 'al_cpp': D('6.09'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_13: {'al_simples': D('15.20'), 'al_irpj': D('0.71'), 'al_csll': D('0.70'), 'al_cofins': D('2.10'), 'al_pis': D('0.50'), 'al_cpp': D('6.19'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_14: {'al_simples': D('15.35'), 'al_irpj': D('0.71'), 'al_csll': D('0.70'), 'al_cofins': D('2.13'), 'al_pis': D('0.51'), 'al_cpp': D('6.30'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_15: {'al_simples': D('15.48'), 'al_irpj': D('0.72'), 'al_csll': D('0.70'), 'al_cofins': D('2.15'), 'al_pis': D('0.51'), 'al_cpp': D('6.40'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_16: {'al_simples': D('16.85'), 'al_irpj': D('0.78'), 'al_csll': D('0.76'), 'al_cofins': D('2.34'), 'al_pis': D('0.56'), 'al_cpp': D('7.41'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_17: {'al_simples': D('16.98'), 'al_irpj': D('0.78'), 'al_csll': D('0.78'), 'al_cofins': D('2.36'), 'al_pis': D('0.56'), 'al_cpp': D('7.50'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_18: {'al_simples': D('17.13'), 'al_irpj': D('0.80'), 'al_csll': D('0.79'), 'al_cofins': D('2.37'), 'al_pis': D('0.57'), 'al_cpp': D('7.60'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_19: {'al_simples': D('17.27'), 'al_irpj': D('0.80'), 'al_csll': D('0.79'), 'al_cofins': D('2.40'), 'al_pis': D('0.57'), 'al_cpp': D('7.71'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_20: {'al_simples': D('17.42'), 'al_irpj': D('0.81'), 'al_csll': D('0.79'), 'al_cofins': D('2.42'), 'al_pis': D('0.57'), 'al_cpp': D('7.83'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
}

SIMPLES_NACIONAL_ANEXO_04 = {
    SIMPLES_NACIONAL_TETO_01: {'al_simples':  D('4.50'), 'al_irpj': D('0.00'), 'al_csll': D('1.22'), 'al_cofins': D('1.28'), 'al_pis': D('0.00'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_02: {'al_simples':  D('6.54'), 'al_irpj': D('0.00'), 'al_csll': D('1.84'), 'al_cofins': D('1.91'), 'al_pis': D('0.00'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_03: {'al_simples':  D('7.70'), 'al_irpj': D('0.16'), 'al_csll': D('1.85'), 'al_cofins': D('1.95'), 'al_pis': D('0.24'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_04: {'al_simples':  D('8.49'), 'al_irpj': D('0.52'), 'al_csll': D('1.87'), 'al_cofins': D('1.99'), 'al_pis': D('0.27'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_05: {'al_simples':  D('8.97'), 'al_irpj': D('0.89'), 'al_csll': D('1.89'), 'al_cofins': D('2.03'), 'al_pis': D('0.29'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_06: {'al_simples':  D('9.78'), 'al_irpj': D('1.25'), 'al_csll': D('1.91'), 'al_cofins': D('2.07'), 'al_pis': D('0.32'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_07: {'al_simples': D('10.26'), 'al_irpj': D('1.62'), 'al_csll': D('1.93'), 'al_cofins': D('2.11'), 'al_pis': D('0.34'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_08: {'al_simples': D('10.76'), 'al_irpj': D('2.00'), 'al_csll': D('1.95'), 'al_cofins': D('2.15'), 'al_pis': D('0.35'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_09: {'al_simples': D('11.51'), 'al_irpj': D('2.37'), 'al_csll': D('1.97'), 'al_cofins': D('2.19'), 'al_pis': D('0.37'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_10: {'al_simples': D('12.00'), 'al_irpj': D('2.74'), 'al_csll': D('2.00'), 'al_cofins': D('2.23'), 'al_pis': D('0.38'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_11: {'al_simples': D('12.80'), 'al_irpj': D('3.12'), 'al_csll': D('2.01'), 'al_cofins': D('2.27'), 'al_pis': D('0.40'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_12: {'al_simples': D('13.25'), 'al_irpj': D('3.49'), 'al_csll': D('2.03'), 'al_cofins': D('2.31'), 'al_pis': D('0.42'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_13: {'al_simples': D('13.70'), 'al_irpj': D('3.86'), 'al_csll': D('2.05'), 'al_cofins': D('2.35'), 'al_pis': D('0.44'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_14: {'al_simples': D('14.15'), 'al_irpj': D('4.23'), 'al_csll': D('2.07'), 'al_cofins': D('2.39'), 'al_pis': D('0.46'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_15: {'al_simples': D('14.60'), 'al_irpj': D('4.60'), 'al_csll': D('2.10'), 'al_cofins': D('2.43'), 'al_pis': D('0.47'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_16: {'al_simples': D('15.05'), 'al_irpj': D('4.90'), 'al_csll': D('2.19'), 'al_cofins': D('2.47'), 'al_pis': D('0.49'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_17: {'al_simples': D('15.50'), 'al_irpj': D('5.21'), 'al_csll': D('2.27'), 'al_cofins': D('2.51'), 'al_pis': D('0.51'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_18: {'al_simples': D('15.95'), 'al_irpj': D('5.51'), 'al_csll': D('2.36'), 'al_cofins': D('2.55'), 'al_pis': D('0.53'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_19: {'al_simples': D('16.40'), 'al_irpj': D('5.81'), 'al_csll': D('2.45'), 'al_cofins': D('2.59'), 'al_pis': D('0.55'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_20: {'al_simples': D('16.85'), 'al_irpj': D('6.12'), 'al_csll': D('2.53'), 'al_cofins': D('2.63'), 'al_pis': D('0.57'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
}

SIMPLES_NACIONAL_ANEXO_06 = {
    SIMPLES_NACIONAL_TETO_01: {'al_simples': D('16.93'), 'al_irpj': D('7.71'), 'al_csll': D('3.19'), 'al_cofins': D('3.31'), 'al_pis': D('0.72'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_02: {'al_simples': D('17.72'), 'al_irpj': D('7.71'), 'al_csll': D('3.19'), 'al_cofins': D('3.31'), 'al_pis': D('0.72'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_03: {'al_simples': D('18.43'), 'al_irpj': D('7.71'), 'al_csll': D('3.19'), 'al_cofins': D('3.31'), 'al_pis': D('0.72'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_04: {'al_simples': D('18.77'), 'al_irpj': D('7.71'), 'al_csll': D('3.19'), 'al_cofins': D('3.31'), 'al_pis': D('0.72'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_05: {'al_simples': D('19.04'), 'al_irpj': D('7.83'), 'al_csll': D('3.24'), 'al_cofins': D('3.37'), 'al_pis': D('0.73'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_06: {'al_simples': D('19.94'), 'al_irpj': D('8.11'), 'al_csll': D('3.35'), 'al_cofins': D('3.49'), 'al_pis': D('0.76'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_07: {'al_simples': D('20.34'), 'al_irpj': D('8.31'), 'al_csll': D('3.43'), 'al_cofins': D('3.57'), 'al_pis': D('0.77'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_08: {'al_simples': D('20.66'), 'al_irpj': D('8.44'), 'al_csll': D('3.49'), 'al_cofins': D('3.63'), 'al_pis': D('0.79'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_09: {'al_simples': D('21.17'), 'al_irpj': D('8.54'), 'al_csll': D('3.54'), 'al_cofins': D('3.68'), 'al_pis': D('0.80'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_10: {'al_simples': D('21.38'), 'al_irpj': D('8.65'), 'al_csll': D('3.57'), 'al_cofins': D('3.71'), 'al_pis': D('0.80'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_11: {'al_simples': D('21.86'), 'al_irpj': D('8.71'), 'al_csll': D('3.60'), 'al_cofins': D('3.74'), 'al_pis': D('0.81'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_12: {'al_simples': D('21.97'), 'al_irpj': D('8.76'), 'al_csll': D('3.62'), 'al_cofins': D('3.77'), 'al_pis': D('0.82'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_13: {'al_simples': D('22.06'), 'al_irpj': D('8.81'), 'al_csll': D('3.64'), 'al_cofins': D('3.79'), 'al_pis': D('0.82'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_14: {'al_simples': D('22.14'), 'al_irpj': D('8.86'), 'al_csll': D('3.66'), 'al_cofins': D('3.80'), 'al_pis': D('0.82'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_15: {'al_simples': D('22.21'), 'al_irpj': D('8.89'), 'al_csll': D('3.67'), 'al_cofins': D('3.82'), 'al_pis': D('0.83'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_16: {'al_simples': D('22.21'), 'al_irpj': D('8.89'), 'al_csll': D('3.67'), 'al_cofins': D('3.82'), 'al_pis': D('0.83'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_17: {'al_simples': D('22.32'), 'al_irpj': D('8.95'), 'al_csll': D('3.70'), 'al_cofins': D('3.84'), 'al_pis': D('0.83'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_18: {'al_simples': D('22.37'), 'al_irpj': D('8.96'), 'al_csll': D('3.71'), 'al_cofins': D('3.86'), 'al_pis': D('0.84'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_19: {'al_simples': D('22.41'), 'al_irpj': D('8.99'), 'al_csll': D('3.72'), 'al_cofins': D('3.86'), 'al_pis': D('0.84'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
    SIMPLES_NACIONAL_TETO_20: {'al_simples': D('22.45'), 'al_irpj': D('9.01'), 'al_csll': D('3.73'), 'al_cofins': D('3.87'), 'al_pis': D('0.84'), 'al_cpp': D('0.00'), 'al_icms': D('0.00'), 'al_iss': D('0.00')},
}

SIMPLES_NACIONAL_TABELAS = {
    '1': SIMPLES_NACIONAL_ANEXO_01,
    '2': SIMPLES_NACIONAL_ANEXO_02,
    '3': SIMPLES_NACIONAL_ANEXO_03,
    '4': SIMPLES_NACIONAL_ANEXO_04,
    '6': SIMPLES_NACIONAL_ANEXO_06,
}
