# -*- coding: utf-8 -*-


#from __future__ import division, print_function, unicode_literals


{
    'name': 'Construcao',
    'version': '1.0',
    'category': 'Integra',
    'description': u'Construção civil',
    'author': 'Integra',
    'maintainer': 'Integra',
    'website': 'http://www.ERPIntegra.com.br',
    'depends': [
        'base',
        'sped_base',
        'sped',
        'project',
        'account',
        'project_long_term',
        'finan',
        'finan_modelo_lancamento',
        'finan_contrato',
        'finan_contrato_checklist',
        'finan_cheque',
        'purchase',
        'compras',
        'sped_purchase',
        'integra_libreoffice',
        'share',
    ],
    'update_xml': [
        'views/mail_compose_message_negociacao_view.xml',

        'views/project_task.xml',
        'views/project_etapa.xml',
        'views/project_orcamento.xml',
        'views/project_orcamento_planejamento.xml',
        'views/purchase_orcamento_planejamento.xml',
        'views/purchase_orcamento_item.xml',
        'views/project_orcamento_medicao.xml',
        'views/res_partner_address_view.xml',
        'views/res_cep_view.xml',
        'views/partner_view.xml',
        'views/res_partner_corretor_view.xml',
        'views/res_partner_contato_view.xml',

        'views/crm_lead_prospecto_view.xml',

        'views/imovel_view.xml',
        'views/imovel_casa.xml',
        'views/imovel_apartamento.xml',
        'views/imovel_terreno.xml',
        'views/imovel_chacara.xml',
        'views/imovel_fazenda.xml',
        'views/imovel_area.xml',
        'views/imovel_galpao.xml',
        'views/imovel_predio.xml',
        'views/imovel_sala_comercial.xml',
        'views/imovel_loja.xml',
        'views/imovel_outros.xml',
        'views/hr_employee_view.xml',
        'views/product_view.xml',
        'views/p_view.xml',
        'views/purchase_view.xml',
        'views/purchase_cotacao.xml',
        'views/cotacao_supplier_info.xml',
        'views/purchase_solicitacao_cotacao.xml',
        'views/purchase_solicitacao_item.xml',
        'views/purchase_order.xml',
        'views/purchase_order_line_view.xml',
        #'views/finan_tabela_venda.xml',
        'views/imovel_crm.xml',

        'views/finan_contrato_etapa.xml',
        'views/finan_contrato_condicao_pagamento_view.xml',
        'views/finan_contrato_condicao_pagamento_renegociacao_view.xml',
        'views/finan_contrato_proposta.xml',
        'views/finan_contrato_analise_financeiro.xml',
        'views/finan_contrato_analise_juridico.xml',
        'views/finan_contrato_receber_view.xml',

        'views/finan_centrocusto_view.xml',
        'views/finan_pagar_view.xml',
        'views/finan_receber_view.xml',
        'views/finan_documento_view.xml',
        'views/project_view.xml',
        'views/const_zoneamento.xml',
        'views/finan_comissao.xml',

        'views/sped_documento_nfe_recebida.xml',
        'views/sped_documento_nfe_recebida_manual.xml',
        'views/sped_documento_nfse_recebida.xml',
        'views/sped_documento_ecf_recebido.xml',
        'views/lo_modelo.xml',

        'wizard/relatorio_projeto_tarefa.xml',
        'wizard/relatorio_projeto_orcamento.xml',
        'wizard/relatorio_projeto_orcamento_compras.xml',
        'wizard/relatorio_orcamento_prefeitura.xml',
        'wizard/relatorio_cronograma_desembolso.xml',
        'wizard/relatorio_cronograma_fisico_gantt.xml',
        'wizard/finan_relatorio_pagar.xml',
        'wizard/finan_relatorio_diario_fornecedor_rateio.xml',
        'wizard/finan_relatorio_diario_cliente_rateio.xml',
        'wizard/finan_pagar_sintetico_rateio_view.xml',
        'wizard/finan_relatorio_movimentacao.xml',

        'wizard/res_users_imovel_wizard.xml',

        'views/bi_view.xml',
        'views/finan_contrato_dashboard_view.xml',

    ],
    'init_xml': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}

